// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module NN_conv2_Pipeline_VITIS_LOOP_173_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        conv_out_26_address0,
        conv_out_26_ce0,
        conv_out_26_we0,
        conv_out_26_d0,
        conv_out_25_address0,
        conv_out_25_ce0,
        conv_out_25_we0,
        conv_out_25_d0,
        conv_out_24_address0,
        conv_out_24_ce0,
        conv_out_24_we0,
        conv_out_24_d0,
        conv_out_23_address0,
        conv_out_23_ce0,
        conv_out_23_we0,
        conv_out_23_d0,
        conv_out_22_address0,
        conv_out_22_ce0,
        conv_out_22_we0,
        conv_out_22_d0,
        conv_out_21_address0,
        conv_out_21_ce0,
        conv_out_21_we0,
        conv_out_21_d0,
        conv_out_20_address0,
        conv_out_20_ce0,
        conv_out_20_we0,
        conv_out_20_d0,
        conv_out_19_address0,
        conv_out_19_ce0,
        conv_out_19_we0,
        conv_out_19_d0,
        conv_out_18_address0,
        conv_out_18_ce0,
        conv_out_18_we0,
        conv_out_18_d0,
        conv_out_17_address0,
        conv_out_17_ce0,
        conv_out_17_we0,
        conv_out_17_d0,
        conv_out_16_address0,
        conv_out_16_ce0,
        conv_out_16_we0,
        conv_out_16_d0,
        conv_out_15_address0,
        conv_out_15_ce0,
        conv_out_15_we0,
        conv_out_15_d0,
        conv_out_14_address0,
        conv_out_14_ce0,
        conv_out_14_we0,
        conv_out_14_d0,
        conv_out_13_address0,
        conv_out_13_ce0,
        conv_out_13_we0,
        conv_out_13_d0,
        conv_out_12_address0,
        conv_out_12_ce0,
        conv_out_12_we0,
        conv_out_12_d0,
        conv_out_11_address0,
        conv_out_11_ce0,
        conv_out_11_we0,
        conv_out_11_d0,
        conv_out_10_address0,
        conv_out_10_ce0,
        conv_out_10_we0,
        conv_out_10_d0,
        conv_out_9_address0,
        conv_out_9_ce0,
        conv_out_9_we0,
        conv_out_9_d0,
        conv_out_8_address0,
        conv_out_8_ce0,
        conv_out_8_we0,
        conv_out_8_d0,
        conv_out_7_address0,
        conv_out_7_ce0,
        conv_out_7_we0,
        conv_out_7_d0,
        conv_out_6_address0,
        conv_out_6_ce0,
        conv_out_6_we0,
        conv_out_6_d0,
        conv_out_5_address0,
        conv_out_5_ce0,
        conv_out_5_we0,
        conv_out_5_d0,
        conv_out_4_address0,
        conv_out_4_ce0,
        conv_out_4_we0,
        conv_out_4_d0,
        conv_out_3_address0,
        conv_out_3_ce0,
        conv_out_3_we0,
        conv_out_3_d0,
        conv_out_2_address0,
        conv_out_2_ce0,
        conv_out_2_we0,
        conv_out_2_d0,
        conv_out_1_address0,
        conv_out_1_ce0,
        conv_out_1_we0,
        conv_out_1_d0,
        conv_out_address0,
        conv_out_ce0,
        conv_out_we0,
        conv_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] conv_out_26_address0;
output   conv_out_26_ce0;
output   conv_out_26_we0;
output  [31:0] conv_out_26_d0;
output  [4:0] conv_out_25_address0;
output   conv_out_25_ce0;
output   conv_out_25_we0;
output  [31:0] conv_out_25_d0;
output  [4:0] conv_out_24_address0;
output   conv_out_24_ce0;
output   conv_out_24_we0;
output  [31:0] conv_out_24_d0;
output  [4:0] conv_out_23_address0;
output   conv_out_23_ce0;
output   conv_out_23_we0;
output  [31:0] conv_out_23_d0;
output  [4:0] conv_out_22_address0;
output   conv_out_22_ce0;
output   conv_out_22_we0;
output  [31:0] conv_out_22_d0;
output  [4:0] conv_out_21_address0;
output   conv_out_21_ce0;
output   conv_out_21_we0;
output  [31:0] conv_out_21_d0;
output  [4:0] conv_out_20_address0;
output   conv_out_20_ce0;
output   conv_out_20_we0;
output  [31:0] conv_out_20_d0;
output  [4:0] conv_out_19_address0;
output   conv_out_19_ce0;
output   conv_out_19_we0;
output  [31:0] conv_out_19_d0;
output  [4:0] conv_out_18_address0;
output   conv_out_18_ce0;
output   conv_out_18_we0;
output  [31:0] conv_out_18_d0;
output  [4:0] conv_out_17_address0;
output   conv_out_17_ce0;
output   conv_out_17_we0;
output  [31:0] conv_out_17_d0;
output  [4:0] conv_out_16_address0;
output   conv_out_16_ce0;
output   conv_out_16_we0;
output  [31:0] conv_out_16_d0;
output  [4:0] conv_out_15_address0;
output   conv_out_15_ce0;
output   conv_out_15_we0;
output  [31:0] conv_out_15_d0;
output  [4:0] conv_out_14_address0;
output   conv_out_14_ce0;
output   conv_out_14_we0;
output  [31:0] conv_out_14_d0;
output  [4:0] conv_out_13_address0;
output   conv_out_13_ce0;
output   conv_out_13_we0;
output  [31:0] conv_out_13_d0;
output  [4:0] conv_out_12_address0;
output   conv_out_12_ce0;
output   conv_out_12_we0;
output  [31:0] conv_out_12_d0;
output  [4:0] conv_out_11_address0;
output   conv_out_11_ce0;
output   conv_out_11_we0;
output  [31:0] conv_out_11_d0;
output  [4:0] conv_out_10_address0;
output   conv_out_10_ce0;
output   conv_out_10_we0;
output  [31:0] conv_out_10_d0;
output  [4:0] conv_out_9_address0;
output   conv_out_9_ce0;
output   conv_out_9_we0;
output  [31:0] conv_out_9_d0;
output  [4:0] conv_out_8_address0;
output   conv_out_8_ce0;
output   conv_out_8_we0;
output  [31:0] conv_out_8_d0;
output  [4:0] conv_out_7_address0;
output   conv_out_7_ce0;
output   conv_out_7_we0;
output  [31:0] conv_out_7_d0;
output  [4:0] conv_out_6_address0;
output   conv_out_6_ce0;
output   conv_out_6_we0;
output  [31:0] conv_out_6_d0;
output  [4:0] conv_out_5_address0;
output   conv_out_5_ce0;
output   conv_out_5_we0;
output  [31:0] conv_out_5_d0;
output  [4:0] conv_out_4_address0;
output   conv_out_4_ce0;
output   conv_out_4_we0;
output  [31:0] conv_out_4_d0;
output  [4:0] conv_out_3_address0;
output   conv_out_3_ce0;
output   conv_out_3_we0;
output  [31:0] conv_out_3_d0;
output  [4:0] conv_out_2_address0;
output   conv_out_2_ce0;
output   conv_out_2_we0;
output  [31:0] conv_out_2_d0;
output  [4:0] conv_out_1_address0;
output   conv_out_1_ce0;
output   conv_out_1_we0;
output  [31:0] conv_out_1_d0;
output  [4:0] conv_out_address0;
output   conv_out_ce0;
output   conv_out_we0;
output  [31:0] conv_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln173_fu_557_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln173_fu_588_p1;
wire    ap_block_pp0_stage0;
reg   [9:0] phi_urem312_fu_146;
wire   [9:0] select_ln173_fu_635_p3;
wire    ap_block_pp0_stage0_11001;
wire    ap_loop_init;
reg   [19:0] phi_mul310_fu_150;
wire   [19:0] add_ln173_1_fu_572_p2;
reg   [9:0] i_10_fu_154;
wire   [9:0] add_ln173_fu_563_p2;
reg    conv_out_25_we0_local;
wire   [4:0] trunc_ln173_fu_619_p1;
reg    conv_out_25_ce0_local;
reg    conv_out_24_we0_local;
reg    conv_out_24_ce0_local;
reg    conv_out_23_we0_local;
reg    conv_out_23_ce0_local;
reg    conv_out_22_we0_local;
reg    conv_out_22_ce0_local;
reg    conv_out_21_we0_local;
reg    conv_out_21_ce0_local;
reg    conv_out_20_we0_local;
reg    conv_out_20_ce0_local;
reg    conv_out_19_we0_local;
reg    conv_out_19_ce0_local;
reg    conv_out_18_we0_local;
reg    conv_out_18_ce0_local;
reg    conv_out_17_we0_local;
reg    conv_out_17_ce0_local;
reg    conv_out_16_we0_local;
reg    conv_out_16_ce0_local;
reg    conv_out_15_we0_local;
reg    conv_out_15_ce0_local;
reg    conv_out_14_we0_local;
reg    conv_out_14_ce0_local;
reg    conv_out_13_we0_local;
reg    conv_out_13_ce0_local;
reg    conv_out_12_we0_local;
reg    conv_out_12_ce0_local;
reg    conv_out_11_we0_local;
reg    conv_out_11_ce0_local;
reg    conv_out_10_we0_local;
reg    conv_out_10_ce0_local;
reg    conv_out_9_we0_local;
reg    conv_out_9_ce0_local;
reg    conv_out_8_we0_local;
reg    conv_out_8_ce0_local;
reg    conv_out_7_we0_local;
reg    conv_out_7_ce0_local;
reg    conv_out_6_we0_local;
reg    conv_out_6_ce0_local;
reg    conv_out_5_we0_local;
reg    conv_out_5_ce0_local;
reg    conv_out_4_we0_local;
reg    conv_out_4_ce0_local;
reg    conv_out_3_we0_local;
reg    conv_out_3_ce0_local;
reg    conv_out_2_we0_local;
reg    conv_out_2_ce0_local;
reg    conv_out_1_we0_local;
reg    conv_out_1_ce0_local;
reg    conv_out_we0_local;
reg    conv_out_ce0_local;
reg    conv_out_26_we0_local;
reg    conv_out_26_ce0_local;
wire   [4:0] tmp_fu_578_p4;
wire   [0:0] icmp_ln173_1_fu_629_p2;
wire   [9:0] add_ln173_2_fu_623_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 phi_urem312_fu_146 = 10'd0;
#0 phi_mul310_fu_150 = 20'd0;
#0 i_10_fu_154 = 10'd0;
#0 ap_done_reg = 1'b0;
end

NN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_10_fu_154 <= 10'd0;
        end else if (((icmp_ln173_fu_557_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_10_fu_154 <= add_ln173_fu_563_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul310_fu_150 <= 20'd0;
        end else if (((icmp_ln173_fu_557_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_mul310_fu_150 <= add_ln173_1_fu_572_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_urem312_fu_146 <= 10'd0;
        end else if (((icmp_ln173_fu_557_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            phi_urem312_fu_146 <= select_ln173_fu_635_p3;
        end
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_10_ce0_local = 1'b1;
    end else begin
        conv_out_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_10_we0_local = 1'b1;
    end else begin
        conv_out_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_11_ce0_local = 1'b1;
    end else begin
        conv_out_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd11) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_11_we0_local = 1'b1;
    end else begin
        conv_out_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_12_ce0_local = 1'b1;
    end else begin
        conv_out_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_12_we0_local = 1'b1;
    end else begin
        conv_out_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_13_ce0_local = 1'b1;
    end else begin
        conv_out_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd13) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_13_we0_local = 1'b1;
    end else begin
        conv_out_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_14_ce0_local = 1'b1;
    end else begin
        conv_out_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd14) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_14_we0_local = 1'b1;
    end else begin
        conv_out_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_15_ce0_local = 1'b1;
    end else begin
        conv_out_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd15) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_15_we0_local = 1'b1;
    end else begin
        conv_out_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_16_ce0_local = 1'b1;
    end else begin
        conv_out_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_16_we0_local = 1'b1;
    end else begin
        conv_out_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_17_ce0_local = 1'b1;
    end else begin
        conv_out_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd17) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_17_we0_local = 1'b1;
    end else begin
        conv_out_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_18_ce0_local = 1'b1;
    end else begin
        conv_out_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd18) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_18_we0_local = 1'b1;
    end else begin
        conv_out_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_19_ce0_local = 1'b1;
    end else begin
        conv_out_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd19) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_19_we0_local = 1'b1;
    end else begin
        conv_out_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_1_ce0_local = 1'b1;
    end else begin
        conv_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_1_we0_local = 1'b1;
    end else begin
        conv_out_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_20_ce0_local = 1'b1;
    end else begin
        conv_out_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd20) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_20_we0_local = 1'b1;
    end else begin
        conv_out_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_21_ce0_local = 1'b1;
    end else begin
        conv_out_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd21) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_21_we0_local = 1'b1;
    end else begin
        conv_out_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_22_ce0_local = 1'b1;
    end else begin
        conv_out_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd22) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_22_we0_local = 1'b1;
    end else begin
        conv_out_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_23_ce0_local = 1'b1;
    end else begin
        conv_out_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd23) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_23_we0_local = 1'b1;
    end else begin
        conv_out_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_24_ce0_local = 1'b1;
    end else begin
        conv_out_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd24) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_24_we0_local = 1'b1;
    end else begin
        conv_out_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_25_ce0_local = 1'b1;
    end else begin
        conv_out_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd25) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_25_we0_local = 1'b1;
    end else begin
        conv_out_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_26_ce0_local = 1'b1;
    end else begin
        conv_out_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((((((icmp_ln173_fu_557_p2 == 1'd0) & (trunc_ln173_fu_619_p1 == 5'd30)) | ((icmp_ln173_fu_557_p2 == 1'd0) & (trunc_ln173_fu_619_p1 == 5'd31))) | ((icmp_ln173_fu_557_p2 == 1'd0) & (trunc_ln173_fu_619_p1 == 5'd29))) | ((icmp_ln173_fu_557_p2 == 1'd0) & (trunc_ln173_fu_619_p1 == 5'd28))) | ((icmp_ln173_fu_557_p2 == 1'd0) & (trunc_ln173_fu_619_p1 == 5'd27))) | ((icmp_ln173_fu_557_p2 == 1'd0) & (trunc_ln173_fu_619_p1 == 5'd26))))) begin
        conv_out_26_we0_local = 1'b1;
    end else begin
        conv_out_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_2_ce0_local = 1'b1;
    end else begin
        conv_out_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_2_we0_local = 1'b1;
    end else begin
        conv_out_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_3_ce0_local = 1'b1;
    end else begin
        conv_out_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_3_we0_local = 1'b1;
    end else begin
        conv_out_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_4_ce0_local = 1'b1;
    end else begin
        conv_out_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_4_we0_local = 1'b1;
    end else begin
        conv_out_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_5_ce0_local = 1'b1;
    end else begin
        conv_out_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_5_we0_local = 1'b1;
    end else begin
        conv_out_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_6_ce0_local = 1'b1;
    end else begin
        conv_out_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_6_we0_local = 1'b1;
    end else begin
        conv_out_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_7_ce0_local = 1'b1;
    end else begin
        conv_out_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_7_we0_local = 1'b1;
    end else begin
        conv_out_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_8_ce0_local = 1'b1;
    end else begin
        conv_out_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_8_we0_local = 1'b1;
    end else begin
        conv_out_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_9_ce0_local = 1'b1;
    end else begin
        conv_out_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd9) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_9_we0_local = 1'b1;
    end else begin
        conv_out_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_ce0_local = 1'b1;
    end else begin
        conv_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln173_fu_557_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln173_fu_619_p1 == 5'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv_out_we0_local = 1'b1;
    end else begin
        conv_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln173_1_fu_572_p2 = (phi_mul310_fu_150 + 20'd1214);

assign add_ln173_2_fu_623_p2 = (phi_urem312_fu_146 + 10'd1);

assign add_ln173_fu_563_p2 = (i_10_fu_154 + 10'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign conv_out_10_address0 = zext_ln173_fu_588_p1;

assign conv_out_10_ce0 = conv_out_10_ce0_local;

assign conv_out_10_d0 = 32'd0;

assign conv_out_10_we0 = conv_out_10_we0_local;

assign conv_out_11_address0 = zext_ln173_fu_588_p1;

assign conv_out_11_ce0 = conv_out_11_ce0_local;

assign conv_out_11_d0 = 32'd0;

assign conv_out_11_we0 = conv_out_11_we0_local;

assign conv_out_12_address0 = zext_ln173_fu_588_p1;

assign conv_out_12_ce0 = conv_out_12_ce0_local;

assign conv_out_12_d0 = 32'd0;

assign conv_out_12_we0 = conv_out_12_we0_local;

assign conv_out_13_address0 = zext_ln173_fu_588_p1;

assign conv_out_13_ce0 = conv_out_13_ce0_local;

assign conv_out_13_d0 = 32'd0;

assign conv_out_13_we0 = conv_out_13_we0_local;

assign conv_out_14_address0 = zext_ln173_fu_588_p1;

assign conv_out_14_ce0 = conv_out_14_ce0_local;

assign conv_out_14_d0 = 32'd0;

assign conv_out_14_we0 = conv_out_14_we0_local;

assign conv_out_15_address0 = zext_ln173_fu_588_p1;

assign conv_out_15_ce0 = conv_out_15_ce0_local;

assign conv_out_15_d0 = 32'd0;

assign conv_out_15_we0 = conv_out_15_we0_local;

assign conv_out_16_address0 = zext_ln173_fu_588_p1;

assign conv_out_16_ce0 = conv_out_16_ce0_local;

assign conv_out_16_d0 = 32'd0;

assign conv_out_16_we0 = conv_out_16_we0_local;

assign conv_out_17_address0 = zext_ln173_fu_588_p1;

assign conv_out_17_ce0 = conv_out_17_ce0_local;

assign conv_out_17_d0 = 32'd0;

assign conv_out_17_we0 = conv_out_17_we0_local;

assign conv_out_18_address0 = zext_ln173_fu_588_p1;

assign conv_out_18_ce0 = conv_out_18_ce0_local;

assign conv_out_18_d0 = 32'd0;

assign conv_out_18_we0 = conv_out_18_we0_local;

assign conv_out_19_address0 = zext_ln173_fu_588_p1;

assign conv_out_19_ce0 = conv_out_19_ce0_local;

assign conv_out_19_d0 = 32'd0;

assign conv_out_19_we0 = conv_out_19_we0_local;

assign conv_out_1_address0 = zext_ln173_fu_588_p1;

assign conv_out_1_ce0 = conv_out_1_ce0_local;

assign conv_out_1_d0 = 32'd0;

assign conv_out_1_we0 = conv_out_1_we0_local;

assign conv_out_20_address0 = zext_ln173_fu_588_p1;

assign conv_out_20_ce0 = conv_out_20_ce0_local;

assign conv_out_20_d0 = 32'd0;

assign conv_out_20_we0 = conv_out_20_we0_local;

assign conv_out_21_address0 = zext_ln173_fu_588_p1;

assign conv_out_21_ce0 = conv_out_21_ce0_local;

assign conv_out_21_d0 = 32'd0;

assign conv_out_21_we0 = conv_out_21_we0_local;

assign conv_out_22_address0 = zext_ln173_fu_588_p1;

assign conv_out_22_ce0 = conv_out_22_ce0_local;

assign conv_out_22_d0 = 32'd0;

assign conv_out_22_we0 = conv_out_22_we0_local;

assign conv_out_23_address0 = zext_ln173_fu_588_p1;

assign conv_out_23_ce0 = conv_out_23_ce0_local;

assign conv_out_23_d0 = 32'd0;

assign conv_out_23_we0 = conv_out_23_we0_local;

assign conv_out_24_address0 = zext_ln173_fu_588_p1;

assign conv_out_24_ce0 = conv_out_24_ce0_local;

assign conv_out_24_d0 = 32'd0;

assign conv_out_24_we0 = conv_out_24_we0_local;

assign conv_out_25_address0 = zext_ln173_fu_588_p1;

assign conv_out_25_ce0 = conv_out_25_ce0_local;

assign conv_out_25_d0 = 32'd0;

assign conv_out_25_we0 = conv_out_25_we0_local;

assign conv_out_26_address0 = zext_ln173_fu_588_p1;

assign conv_out_26_ce0 = conv_out_26_ce0_local;

assign conv_out_26_d0 = 32'd0;

assign conv_out_26_we0 = conv_out_26_we0_local;

assign conv_out_2_address0 = zext_ln173_fu_588_p1;

assign conv_out_2_ce0 = conv_out_2_ce0_local;

assign conv_out_2_d0 = 32'd0;

assign conv_out_2_we0 = conv_out_2_we0_local;

assign conv_out_3_address0 = zext_ln173_fu_588_p1;

assign conv_out_3_ce0 = conv_out_3_ce0_local;

assign conv_out_3_d0 = 32'd0;

assign conv_out_3_we0 = conv_out_3_we0_local;

assign conv_out_4_address0 = zext_ln173_fu_588_p1;

assign conv_out_4_ce0 = conv_out_4_ce0_local;

assign conv_out_4_d0 = 32'd0;

assign conv_out_4_we0 = conv_out_4_we0_local;

assign conv_out_5_address0 = zext_ln173_fu_588_p1;

assign conv_out_5_ce0 = conv_out_5_ce0_local;

assign conv_out_5_d0 = 32'd0;

assign conv_out_5_we0 = conv_out_5_we0_local;

assign conv_out_6_address0 = zext_ln173_fu_588_p1;

assign conv_out_6_ce0 = conv_out_6_ce0_local;

assign conv_out_6_d0 = 32'd0;

assign conv_out_6_we0 = conv_out_6_we0_local;

assign conv_out_7_address0 = zext_ln173_fu_588_p1;

assign conv_out_7_ce0 = conv_out_7_ce0_local;

assign conv_out_7_d0 = 32'd0;

assign conv_out_7_we0 = conv_out_7_we0_local;

assign conv_out_8_address0 = zext_ln173_fu_588_p1;

assign conv_out_8_ce0 = conv_out_8_ce0_local;

assign conv_out_8_d0 = 32'd0;

assign conv_out_8_we0 = conv_out_8_we0_local;

assign conv_out_9_address0 = zext_ln173_fu_588_p1;

assign conv_out_9_ce0 = conv_out_9_ce0_local;

assign conv_out_9_d0 = 32'd0;

assign conv_out_9_we0 = conv_out_9_we0_local;

assign conv_out_address0 = zext_ln173_fu_588_p1;

assign conv_out_ce0 = conv_out_ce0_local;

assign conv_out_d0 = 32'd0;

assign conv_out_we0 = conv_out_we0_local;

assign icmp_ln173_1_fu_629_p2 = ((phi_urem312_fu_146 == 10'd26) ? 1'b1 : 1'b0);

assign icmp_ln173_fu_557_p2 = ((i_10_fu_154 == 10'd729) ? 1'b1 : 1'b0);

assign select_ln173_fu_635_p3 = ((icmp_ln173_1_fu_629_p2[0:0] == 1'b1) ? 10'd0 : add_ln173_2_fu_623_p2);

assign tmp_fu_578_p4 = {{phi_mul310_fu_150[19:15]}};

assign trunc_ln173_fu_619_p1 = phi_urem312_fu_146[4:0];

assign zext_ln173_fu_588_p1 = tmp_fu_578_p4;

endmodule //NN_conv2_Pipeline_VITIS_LOOP_173_7
