// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module NN_norm2_Pipeline_L2_L3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inp_image_address0,
        inp_image_ce0,
        inp_image_q0,
        inp_image_1_address0,
        inp_image_1_ce0,
        inp_image_1_q0,
        inp_image_2_address0,
        inp_image_2_ce0,
        inp_image_2_q0,
        out_img_address0,
        out_img_ce0,
        out_img_we0,
        out_img_d0,
        grp_fu_1944_p_din0,
        grp_fu_1944_p_din1,
        grp_fu_1944_p_opcode,
        grp_fu_1944_p_dout0,
        grp_fu_1944_p_ce,
        grp_fu_1948_p_din0,
        grp_fu_1948_p_din1,
        grp_fu_1948_p_opcode,
        grp_fu_1948_p_dout0,
        grp_fu_1948_p_ce,
        grp_fu_1952_p_din0,
        grp_fu_1952_p_din1,
        grp_fu_1952_p_opcode,
        grp_fu_1952_p_dout0,
        grp_fu_1952_p_ce,
        grp_fu_1956_p_din0,
        grp_fu_1956_p_din1,
        grp_fu_1956_p_dout0,
        grp_fu_1956_p_ce,
        grp_fu_1960_p_din0,
        grp_fu_1960_p_dout0,
        grp_fu_1960_p_ce,
        grp_fu_1963_p_din0,
        grp_fu_1963_p_dout0,
        grp_fu_1963_p_ce,
        grp_fu_1966_p_din0,
        grp_fu_1966_p_din1,
        grp_fu_1966_p_opcode,
        grp_fu_1966_p_dout0,
        grp_fu_1966_p_ce,
        grp_fu_1970_p_din0,
        grp_fu_1970_p_din1,
        grp_fu_1970_p_dout0,
        grp_fu_1970_p_ce,
        grp_pow_generic_float_s_fu_1974_p_din1,
        grp_pow_generic_float_s_fu_1974_p_din2,
        grp_pow_generic_float_s_fu_1974_p_dout0,
        grp_pow_generic_float_s_fu_1986_p_din1,
        grp_pow_generic_float_s_fu_1986_p_din2,
        grp_pow_generic_float_s_fu_1986_p_dout0,
        grp_pow_generic_float_s_fu_1998_p_din1,
        grp_pow_generic_float_s_fu_1998_p_din2,
        grp_pow_generic_float_s_fu_1998_p_dout0,
        grp_pow_generic_float_s_fu_2010_p_din1,
        grp_pow_generic_float_s_fu_2010_p_din2,
        grp_pow_generic_float_s_fu_2010_p_dout0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] inp_image_address0;
output   inp_image_ce0;
input  [31:0] inp_image_q0;
output  [7:0] inp_image_1_address0;
output   inp_image_1_ce0;
input  [31:0] inp_image_1_q0;
output  [7:0] inp_image_2_address0;
output   inp_image_2_ce0;
input  [31:0] inp_image_2_q0;
output  [15:0] out_img_address0;
output   out_img_ce0;
output   out_img_we0;
output  [31:0] out_img_d0;
output  [31:0] grp_fu_1944_p_din0;
output  [31:0] grp_fu_1944_p_din1;
output  [1:0] grp_fu_1944_p_opcode;
input  [31:0] grp_fu_1944_p_dout0;
output   grp_fu_1944_p_ce;
output  [31:0] grp_fu_1948_p_din0;
output  [31:0] grp_fu_1948_p_din1;
output  [1:0] grp_fu_1948_p_opcode;
input  [31:0] grp_fu_1948_p_dout0;
output   grp_fu_1948_p_ce;
output  [31:0] grp_fu_1952_p_din0;
output  [31:0] grp_fu_1952_p_din1;
output  [1:0] grp_fu_1952_p_opcode;
input  [31:0] grp_fu_1952_p_dout0;
output   grp_fu_1952_p_ce;
output  [31:0] grp_fu_1956_p_din0;
output  [31:0] grp_fu_1956_p_din1;
input  [31:0] grp_fu_1956_p_dout0;
output   grp_fu_1956_p_ce;
output  [63:0] grp_fu_1960_p_din0;
input  [31:0] grp_fu_1960_p_dout0;
output   grp_fu_1960_p_ce;
output  [31:0] grp_fu_1963_p_din0;
input  [63:0] grp_fu_1963_p_dout0;
output   grp_fu_1963_p_ce;
output  [63:0] grp_fu_1966_p_din0;
output  [63:0] grp_fu_1966_p_din1;
output  [1:0] grp_fu_1966_p_opcode;
input  [63:0] grp_fu_1966_p_dout0;
output   grp_fu_1966_p_ce;
output  [63:0] grp_fu_1970_p_din0;
output  [63:0] grp_fu_1970_p_din1;
input  [63:0] grp_fu_1970_p_dout0;
output   grp_fu_1970_p_ce;
output  [31:0] grp_pow_generic_float_s_fu_1974_p_din1;
output  [31:0] grp_pow_generic_float_s_fu_1974_p_din2;
input  [31:0] grp_pow_generic_float_s_fu_1974_p_dout0;
output  [31:0] grp_pow_generic_float_s_fu_1986_p_din1;
output  [31:0] grp_pow_generic_float_s_fu_1986_p_din2;
input  [31:0] grp_pow_generic_float_s_fu_1986_p_dout0;
output  [31:0] grp_pow_generic_float_s_fu_1998_p_din1;
output  [31:0] grp_pow_generic_float_s_fu_1998_p_din2;
input  [31:0] grp_pow_generic_float_s_fu_1998_p_dout0;
output  [31:0] grp_pow_generic_float_s_fu_2010_p_din1;
output  [31:0] grp_pow_generic_float_s_fu_2010_p_din2;
input  [31:0] grp_pow_generic_float_s_fu_2010_p_dout0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg    ap_enable_reg_pp0_iter45;
reg    ap_enable_reg_pp0_iter46;
reg    ap_enable_reg_pp0_iter47;
reg    ap_enable_reg_pp0_iter48;
reg    ap_enable_reg_pp0_iter49;
reg    ap_enable_reg_pp0_iter50;
reg    ap_enable_reg_pp0_iter51;
reg    ap_enable_reg_pp0_iter52;
reg    ap_enable_reg_pp0_iter53;
reg    ap_enable_reg_pp0_iter54;
reg    ap_enable_reg_pp0_iter55;
reg    ap_enable_reg_pp0_iter56;
reg    ap_enable_reg_pp0_iter57;
reg    ap_enable_reg_pp0_iter58;
reg    ap_enable_reg_pp0_iter59;
reg    ap_enable_reg_pp0_iter60;
reg    ap_enable_reg_pp0_iter61;
reg    ap_enable_reg_pp0_iter62;
reg    ap_enable_reg_pp0_iter63;
reg    ap_enable_reg_pp0_iter64;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln59_fu_271_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] select_ln59_fu_301_p3;
reg   [3:0] select_ln59_reg_383;
reg   [3:0] select_ln59_reg_383_pp0_iter1_reg;
wire   [63:0] zext_ln67_2_fu_345_p1;
reg   [63:0] zext_ln67_2_reg_398;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter4_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter5_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter6_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter7_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter8_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter9_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter10_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter11_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter12_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter13_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter14_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter15_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter16_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter17_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter18_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter19_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter20_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter21_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter22_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter23_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter24_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter25_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter26_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter27_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter28_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter29_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter30_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter31_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter32_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter33_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter34_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter35_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter36_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter37_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter38_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter39_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter40_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter41_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter42_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter43_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter44_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter45_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter46_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter47_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter48_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter49_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter50_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter51_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter52_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter53_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter54_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter55_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter56_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter57_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter58_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter59_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter60_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter61_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter62_reg;
reg   [63:0] zext_ln67_2_reg_398_pp0_iter63_reg;
reg   [31:0] inp_image_load_reg_410;
reg   [31:0] inp_image_load_reg_410_pp0_iter5_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter6_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter7_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter8_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter9_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter10_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter11_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter12_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter13_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter14_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter15_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter16_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter17_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter18_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter19_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter20_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter21_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter22_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter23_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter24_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter25_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter26_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter27_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter28_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter29_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter30_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter31_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter32_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter33_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter34_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter35_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter36_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter37_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter38_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter39_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter40_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter41_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter42_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter43_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter44_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter45_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter46_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter47_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter48_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter49_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter50_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter51_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter52_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter53_reg;
reg   [31:0] inp_image_load_reg_410_pp0_iter54_reg;
reg   [31:0] tmp_reg_436;
wire    ap_block_pp0_stage0_11001_ignoreCallOp130;
reg   [31:0] add_reg_441;
reg   [31:0] tmp_s_reg_446;
wire    ap_block_pp0_stage0_11001_ignoreCallOp143;
reg   [31:0] add51_1_reg_451;
reg   [31:0] tmp_11_reg_456;
wire    ap_block_pp0_stage0_11001_ignoreCallOp152;
reg   [31:0] add51_2_reg_461;
reg   [63:0] conv_reg_466;
reg   [63:0] mul_reg_471;
reg   [63:0] add1_reg_476;
reg   [31:0] tmp_12_reg_486;
wire    ap_block_pp0_stage0_11001_ignoreCallOp183;
reg   [31:0] div_reg_491;
wire    ap_block_pp0_stage0_ignoreCallOp100;
wire    ap_block_pp0_stage0_ignoreCallOp108;
wire    ap_block_pp0_stage0_ignoreCallOp120;
wire    ap_block_pp0_stage0_ignoreCallOp171;
wire    ap_block_pp0_stage0;
reg   [3:0] y_fu_68;
wire   [3:0] add_ln62_fu_321_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_y_load;
reg   [3:0] x_fu_72;
wire   [3:0] select_ln59_1_fu_309_p3;
reg   [3:0] ap_sig_allocacmp_x_load;
reg   [7:0] indvar_flatten19_fu_76;
wire   [7:0] add_ln59_1_fu_277_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten19_load;
reg    inp_image_ce0_local;
reg    inp_image_1_ce0_local;
reg    inp_image_2_ce0_local;
reg    out_img_we0_local;
reg    out_img_ce0_local;
wire   [0:0] icmp_ln62_fu_295_p2;
wire   [3:0] add_ln59_fu_289_p2;
wire   [7:0] grp_fu_349_p3;
wire   [3:0] grp_fu_349_p0;
wire   [3:0] grp_fu_349_p1;
wire   [3:0] grp_fu_349_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg    ap_loop_exit_ready_pp0_iter41_reg;
reg    ap_loop_exit_ready_pp0_iter42_reg;
reg    ap_loop_exit_ready_pp0_iter43_reg;
reg    ap_loop_exit_ready_pp0_iter44_reg;
reg    ap_loop_exit_ready_pp0_iter45_reg;
reg    ap_loop_exit_ready_pp0_iter46_reg;
reg    ap_loop_exit_ready_pp0_iter47_reg;
reg    ap_loop_exit_ready_pp0_iter48_reg;
reg    ap_loop_exit_ready_pp0_iter49_reg;
reg    ap_loop_exit_ready_pp0_iter50_reg;
reg    ap_loop_exit_ready_pp0_iter51_reg;
reg    ap_loop_exit_ready_pp0_iter52_reg;
reg    ap_loop_exit_ready_pp0_iter53_reg;
reg    ap_loop_exit_ready_pp0_iter54_reg;
reg    ap_loop_exit_ready_pp0_iter55_reg;
reg    ap_loop_exit_ready_pp0_iter56_reg;
reg    ap_loop_exit_ready_pp0_iter57_reg;
reg    ap_loop_exit_ready_pp0_iter58_reg;
reg    ap_loop_exit_ready_pp0_iter59_reg;
reg    ap_loop_exit_ready_pp0_iter60_reg;
reg    ap_loop_exit_ready_pp0_iter61_reg;
reg    ap_loop_exit_ready_pp0_iter62_reg;
reg    ap_loop_exit_ready_pp0_iter63_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_block_pp0_stage0_00001;
wire   [7:0] grp_fu_349_p00;
wire   [7:0] grp_fu_349_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
#0 ap_enable_reg_pp0_iter45 = 1'b0;
#0 ap_enable_reg_pp0_iter46 = 1'b0;
#0 ap_enable_reg_pp0_iter47 = 1'b0;
#0 ap_enable_reg_pp0_iter48 = 1'b0;
#0 ap_enable_reg_pp0_iter49 = 1'b0;
#0 ap_enable_reg_pp0_iter50 = 1'b0;
#0 ap_enable_reg_pp0_iter51 = 1'b0;
#0 ap_enable_reg_pp0_iter52 = 1'b0;
#0 ap_enable_reg_pp0_iter53 = 1'b0;
#0 ap_enable_reg_pp0_iter54 = 1'b0;
#0 ap_enable_reg_pp0_iter55 = 1'b0;
#0 ap_enable_reg_pp0_iter56 = 1'b0;
#0 ap_enable_reg_pp0_iter57 = 1'b0;
#0 ap_enable_reg_pp0_iter58 = 1'b0;
#0 ap_enable_reg_pp0_iter59 = 1'b0;
#0 ap_enable_reg_pp0_iter60 = 1'b0;
#0 ap_enable_reg_pp0_iter61 = 1'b0;
#0 ap_enable_reg_pp0_iter62 = 1'b0;
#0 ap_enable_reg_pp0_iter63 = 1'b0;
#0 ap_enable_reg_pp0_iter64 = 1'b0;
#0 y_fu_68 = 4'd0;
#0 x_fu_72 = 4'd0;
#0 indvar_flatten19_fu_76 = 8'd0;
#0 ap_done_reg = 1'b0;
end

NN_mac_muladd_4ns_4ns_4ns_8_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
mac_muladd_4ns_4ns_4ns_8_4_1_U11445(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_349_p0),
    .din1(grp_fu_349_p1),
    .din2(grp_fu_349_p2),
    .ce(1'b1),
    .dout(grp_fu_349_p3)
);

NN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter63_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter45 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter45 <= ap_enable_reg_pp0_iter44;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter46 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter46 <= ap_enable_reg_pp0_iter45;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter47 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter47 <= ap_enable_reg_pp0_iter46;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter48 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter48 <= ap_enable_reg_pp0_iter47;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter49 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter49 <= ap_enable_reg_pp0_iter48;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter50 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter50 <= ap_enable_reg_pp0_iter49;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter51 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter51 <= ap_enable_reg_pp0_iter50;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter52 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter52 <= ap_enable_reg_pp0_iter51;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter53 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter53 <= ap_enable_reg_pp0_iter52;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter54 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter54 <= ap_enable_reg_pp0_iter53;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter55 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter55 <= ap_enable_reg_pp0_iter54;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter56 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter56 <= ap_enable_reg_pp0_iter55;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter57 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter57 <= ap_enable_reg_pp0_iter56;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter58 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter58 <= ap_enable_reg_pp0_iter57;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter59 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter59 <= ap_enable_reg_pp0_iter58;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter60 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter60 <= ap_enable_reg_pp0_iter59;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter61 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter61 <= ap_enable_reg_pp0_iter60;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter62 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter62 <= ap_enable_reg_pp0_iter61;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter63 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter63 <= ap_enable_reg_pp0_iter62;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter64 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter64 <= ap_enable_reg_pp0_iter63;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln59_fu_271_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten19_fu_76 <= add_ln59_1_fu_277_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten19_fu_76 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln59_fu_271_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_72 <= select_ln59_1_fu_309_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_72 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln59_fu_271_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_68 <= add_ln62_fu_321_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_68 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add1_reg_476 <= grp_fu_1966_p_dout0;
        add51_1_reg_451 <= grp_fu_1948_p_dout0;
        add51_2_reg_461 <= grp_fu_1952_p_dout0;
        add_reg_441 <= grp_fu_1944_p_dout0;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
        ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
        ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
        ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
        ap_loop_exit_ready_pp0_iter44_reg <= ap_loop_exit_ready_pp0_iter43_reg;
        ap_loop_exit_ready_pp0_iter45_reg <= ap_loop_exit_ready_pp0_iter44_reg;
        ap_loop_exit_ready_pp0_iter46_reg <= ap_loop_exit_ready_pp0_iter45_reg;
        ap_loop_exit_ready_pp0_iter47_reg <= ap_loop_exit_ready_pp0_iter46_reg;
        ap_loop_exit_ready_pp0_iter48_reg <= ap_loop_exit_ready_pp0_iter47_reg;
        ap_loop_exit_ready_pp0_iter49_reg <= ap_loop_exit_ready_pp0_iter48_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter50_reg <= ap_loop_exit_ready_pp0_iter49_reg;
        ap_loop_exit_ready_pp0_iter51_reg <= ap_loop_exit_ready_pp0_iter50_reg;
        ap_loop_exit_ready_pp0_iter52_reg <= ap_loop_exit_ready_pp0_iter51_reg;
        ap_loop_exit_ready_pp0_iter53_reg <= ap_loop_exit_ready_pp0_iter52_reg;
        ap_loop_exit_ready_pp0_iter54_reg <= ap_loop_exit_ready_pp0_iter53_reg;
        ap_loop_exit_ready_pp0_iter55_reg <= ap_loop_exit_ready_pp0_iter54_reg;
        ap_loop_exit_ready_pp0_iter56_reg <= ap_loop_exit_ready_pp0_iter55_reg;
        ap_loop_exit_ready_pp0_iter57_reg <= ap_loop_exit_ready_pp0_iter56_reg;
        ap_loop_exit_ready_pp0_iter58_reg <= ap_loop_exit_ready_pp0_iter57_reg;
        ap_loop_exit_ready_pp0_iter59_reg <= ap_loop_exit_ready_pp0_iter58_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter60_reg <= ap_loop_exit_ready_pp0_iter59_reg;
        ap_loop_exit_ready_pp0_iter61_reg <= ap_loop_exit_ready_pp0_iter60_reg;
        ap_loop_exit_ready_pp0_iter62_reg <= ap_loop_exit_ready_pp0_iter61_reg;
        ap_loop_exit_ready_pp0_iter63_reg <= ap_loop_exit_ready_pp0_iter62_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        conv_reg_466 <= grp_fu_1963_p_dout0;
        div_reg_491 <= grp_fu_1956_p_dout0;
        inp_image_load_reg_410 <= inp_image_q0;
        inp_image_load_reg_410_pp0_iter10_reg <= inp_image_load_reg_410_pp0_iter9_reg;
        inp_image_load_reg_410_pp0_iter11_reg <= inp_image_load_reg_410_pp0_iter10_reg;
        inp_image_load_reg_410_pp0_iter12_reg <= inp_image_load_reg_410_pp0_iter11_reg;
        inp_image_load_reg_410_pp0_iter13_reg <= inp_image_load_reg_410_pp0_iter12_reg;
        inp_image_load_reg_410_pp0_iter14_reg <= inp_image_load_reg_410_pp0_iter13_reg;
        inp_image_load_reg_410_pp0_iter15_reg <= inp_image_load_reg_410_pp0_iter14_reg;
        inp_image_load_reg_410_pp0_iter16_reg <= inp_image_load_reg_410_pp0_iter15_reg;
        inp_image_load_reg_410_pp0_iter17_reg <= inp_image_load_reg_410_pp0_iter16_reg;
        inp_image_load_reg_410_pp0_iter18_reg <= inp_image_load_reg_410_pp0_iter17_reg;
        inp_image_load_reg_410_pp0_iter19_reg <= inp_image_load_reg_410_pp0_iter18_reg;
        inp_image_load_reg_410_pp0_iter20_reg <= inp_image_load_reg_410_pp0_iter19_reg;
        inp_image_load_reg_410_pp0_iter21_reg <= inp_image_load_reg_410_pp0_iter20_reg;
        inp_image_load_reg_410_pp0_iter22_reg <= inp_image_load_reg_410_pp0_iter21_reg;
        inp_image_load_reg_410_pp0_iter23_reg <= inp_image_load_reg_410_pp0_iter22_reg;
        inp_image_load_reg_410_pp0_iter24_reg <= inp_image_load_reg_410_pp0_iter23_reg;
        inp_image_load_reg_410_pp0_iter25_reg <= inp_image_load_reg_410_pp0_iter24_reg;
        inp_image_load_reg_410_pp0_iter26_reg <= inp_image_load_reg_410_pp0_iter25_reg;
        inp_image_load_reg_410_pp0_iter27_reg <= inp_image_load_reg_410_pp0_iter26_reg;
        inp_image_load_reg_410_pp0_iter28_reg <= inp_image_load_reg_410_pp0_iter27_reg;
        inp_image_load_reg_410_pp0_iter29_reg <= inp_image_load_reg_410_pp0_iter28_reg;
        inp_image_load_reg_410_pp0_iter30_reg <= inp_image_load_reg_410_pp0_iter29_reg;
        inp_image_load_reg_410_pp0_iter31_reg <= inp_image_load_reg_410_pp0_iter30_reg;
        inp_image_load_reg_410_pp0_iter32_reg <= inp_image_load_reg_410_pp0_iter31_reg;
        inp_image_load_reg_410_pp0_iter33_reg <= inp_image_load_reg_410_pp0_iter32_reg;
        inp_image_load_reg_410_pp0_iter34_reg <= inp_image_load_reg_410_pp0_iter33_reg;
        inp_image_load_reg_410_pp0_iter35_reg <= inp_image_load_reg_410_pp0_iter34_reg;
        inp_image_load_reg_410_pp0_iter36_reg <= inp_image_load_reg_410_pp0_iter35_reg;
        inp_image_load_reg_410_pp0_iter37_reg <= inp_image_load_reg_410_pp0_iter36_reg;
        inp_image_load_reg_410_pp0_iter38_reg <= inp_image_load_reg_410_pp0_iter37_reg;
        inp_image_load_reg_410_pp0_iter39_reg <= inp_image_load_reg_410_pp0_iter38_reg;
        inp_image_load_reg_410_pp0_iter40_reg <= inp_image_load_reg_410_pp0_iter39_reg;
        inp_image_load_reg_410_pp0_iter41_reg <= inp_image_load_reg_410_pp0_iter40_reg;
        inp_image_load_reg_410_pp0_iter42_reg <= inp_image_load_reg_410_pp0_iter41_reg;
        inp_image_load_reg_410_pp0_iter43_reg <= inp_image_load_reg_410_pp0_iter42_reg;
        inp_image_load_reg_410_pp0_iter44_reg <= inp_image_load_reg_410_pp0_iter43_reg;
        inp_image_load_reg_410_pp0_iter45_reg <= inp_image_load_reg_410_pp0_iter44_reg;
        inp_image_load_reg_410_pp0_iter46_reg <= inp_image_load_reg_410_pp0_iter45_reg;
        inp_image_load_reg_410_pp0_iter47_reg <= inp_image_load_reg_410_pp0_iter46_reg;
        inp_image_load_reg_410_pp0_iter48_reg <= inp_image_load_reg_410_pp0_iter47_reg;
        inp_image_load_reg_410_pp0_iter49_reg <= inp_image_load_reg_410_pp0_iter48_reg;
        inp_image_load_reg_410_pp0_iter50_reg <= inp_image_load_reg_410_pp0_iter49_reg;
        inp_image_load_reg_410_pp0_iter51_reg <= inp_image_load_reg_410_pp0_iter50_reg;
        inp_image_load_reg_410_pp0_iter52_reg <= inp_image_load_reg_410_pp0_iter51_reg;
        inp_image_load_reg_410_pp0_iter53_reg <= inp_image_load_reg_410_pp0_iter52_reg;
        inp_image_load_reg_410_pp0_iter54_reg <= inp_image_load_reg_410_pp0_iter53_reg;
        inp_image_load_reg_410_pp0_iter5_reg <= inp_image_load_reg_410;
        inp_image_load_reg_410_pp0_iter6_reg <= inp_image_load_reg_410_pp0_iter5_reg;
        inp_image_load_reg_410_pp0_iter7_reg <= inp_image_load_reg_410_pp0_iter6_reg;
        inp_image_load_reg_410_pp0_iter8_reg <= inp_image_load_reg_410_pp0_iter7_reg;
        inp_image_load_reg_410_pp0_iter9_reg <= inp_image_load_reg_410_pp0_iter8_reg;
        mul_reg_471 <= grp_fu_1970_p_dout0;
        zext_ln67_2_reg_398[7 : 0] <= zext_ln67_2_fu_345_p1[7 : 0];
        zext_ln67_2_reg_398_pp0_iter10_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter9_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter11_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter10_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter12_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter11_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter13_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter12_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter14_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter13_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter15_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter14_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter16_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter15_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter17_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter16_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter18_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter17_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter19_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter18_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter20_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter19_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter21_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter20_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter22_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter21_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter23_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter22_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter24_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter23_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter25_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter24_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter26_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter25_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter27_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter26_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter28_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter27_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter29_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter28_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter30_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter29_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter31_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter30_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter32_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter31_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter33_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter32_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter34_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter33_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter35_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter34_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter36_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter35_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter37_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter36_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter38_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter37_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter39_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter38_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter40_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter39_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter41_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter40_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter42_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter41_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter43_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter42_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter44_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter43_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter45_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter44_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter46_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter45_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter47_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter46_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter48_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter47_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter49_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter48_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter4_reg[7 : 0] <= zext_ln67_2_reg_398[7 : 0];
        zext_ln67_2_reg_398_pp0_iter50_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter49_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter51_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter50_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter52_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter51_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter53_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter52_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter54_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter53_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter55_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter54_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter56_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter55_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter57_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter56_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter58_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter57_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter59_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter58_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter5_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter4_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter60_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter59_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter61_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter60_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter62_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter61_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter63_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter62_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter6_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter5_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter7_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter6_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter8_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter7_reg[7 : 0];
        zext_ln67_2_reg_398_pp0_iter9_reg[7 : 0] <= zext_ln67_2_reg_398_pp0_iter8_reg[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln59_reg_383 <= select_ln59_fu_301_p3;
        select_ln59_reg_383_pp0_iter1_reg <= select_ln59_reg_383;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp152)) begin
        tmp_11_reg_456 <= grp_pow_generic_float_s_fu_1998_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp183)) begin
        tmp_12_reg_486 <= grp_pow_generic_float_s_fu_2010_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp130)) begin
        tmp_reg_436 <= grp_pow_generic_float_s_fu_1974_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp143)) begin
        tmp_s_reg_446 <= grp_pow_generic_float_s_fu_1986_p_dout0;
    end
end

always @ (*) begin
    if (((icmp_ln59_fu_271_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter63_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter64 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) 
    & (ap_enable_reg_pp0_iter63 == 1'b0) & (ap_enable_reg_pp0_iter62 == 1'b0) & (ap_enable_reg_pp0_iter61 == 1'b0) & (ap_enable_reg_pp0_iter60 == 1'b0) & (ap_enable_reg_pp0_iter59 == 1'b0) & (ap_enable_reg_pp0_iter58 == 1'b0) & (ap_enable_reg_pp0_iter57 == 1'b0) & (ap_enable_reg_pp0_iter56 == 1'b0) & (ap_enable_reg_pp0_iter55 == 1'b0) & (ap_enable_reg_pp0_iter54 == 1'b0) & (ap_enable_reg_pp0_iter53 == 1'b0) & (ap_enable_reg_pp0_iter52 == 1'b0) & (ap_enable_reg_pp0_iter51 == 1'b0) & (ap_enable_reg_pp0_iter50 == 1'b0) & (ap_enable_reg_pp0_iter49 == 1'b0) & (ap_enable_reg_pp0_iter48 == 1'b0) & (ap_enable_reg_pp0_iter47 == 1'b0) & (ap_enable_reg_pp0_iter46 == 1'b0) & (ap_enable_reg_pp0_iter45 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 
    == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten19_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten19_load = indvar_flatten19_fu_76;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_load = 4'd0;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_72;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_y_load = 4'd0;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_68;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_image_1_ce0_local = 1'b1;
    end else begin
        inp_image_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_image_2_ce0_local = 1'b1;
    end else begin
        inp_image_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_image_ce0_local = 1'b1;
    end else begin
        inp_image_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter64 == 1'b1))) begin
        out_img_ce0_local = 1'b1;
    end else begin
        out_img_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter64 == 1'b1))) begin
        out_img_we0_local = 1'b1;
    end else begin
        out_img_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln59_1_fu_277_p2 = (ap_sig_allocacmp_indvar_flatten19_load + 8'd1);

assign add_ln59_fu_289_p2 = (ap_sig_allocacmp_x_load + 4'd1);

assign add_ln62_fu_321_p2 = (select_ln59_fu_301_p3 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp130 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp143 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp152 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp183 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp100 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp108 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp120 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp171 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_1944_p_ce = 1'b1;

assign grp_fu_1944_p_din0 = tmp_reg_436;

assign grp_fu_1944_p_din1 = 32'd0;

assign grp_fu_1944_p_opcode = 2'd0;

assign grp_fu_1948_p_ce = 1'b1;

assign grp_fu_1948_p_din0 = add_reg_441;

assign grp_fu_1948_p_din1 = tmp_s_reg_446;

assign grp_fu_1948_p_opcode = 2'd0;

assign grp_fu_1952_p_ce = 1'b1;

assign grp_fu_1952_p_din0 = add51_1_reg_451;

assign grp_fu_1952_p_din1 = tmp_11_reg_456;

assign grp_fu_1952_p_opcode = 2'd0;

assign grp_fu_1956_p_ce = 1'b1;

assign grp_fu_1956_p_din0 = inp_image_load_reg_410_pp0_iter54_reg;

assign grp_fu_1956_p_din1 = tmp_12_reg_486;

assign grp_fu_1960_p_ce = 1'b1;

assign grp_fu_1960_p_din0 = add1_reg_476;

assign grp_fu_1963_p_ce = 1'b1;

assign grp_fu_1963_p_din0 = add51_2_reg_461;

assign grp_fu_1966_p_ce = 1'b1;

assign grp_fu_1966_p_din0 = mul_reg_471;

assign grp_fu_1966_p_din1 = 64'd4607182418800017408;

assign grp_fu_1966_p_opcode = 2'd0;

assign grp_fu_1970_p_ce = 1'b1;

assign grp_fu_1970_p_din0 = conv_reg_466;

assign grp_fu_1970_p_din1 = 64'd4536524183238306033;

assign grp_fu_349_p0 = grp_fu_349_p00;

assign grp_fu_349_p00 = select_ln59_1_fu_309_p3;

assign grp_fu_349_p1 = 8'd13;

assign grp_fu_349_p2 = grp_fu_349_p20;

assign grp_fu_349_p20 = select_ln59_reg_383_pp0_iter1_reg;

assign grp_pow_generic_float_s_fu_1974_p_din1 = inp_image_q0;

assign grp_pow_generic_float_s_fu_1974_p_din2 = 32'd1073741824;

assign grp_pow_generic_float_s_fu_1986_p_din1 = inp_image_1_q0;

assign grp_pow_generic_float_s_fu_1986_p_din2 = 32'd1073741824;

assign grp_pow_generic_float_s_fu_1998_p_din1 = inp_image_2_q0;

assign grp_pow_generic_float_s_fu_1998_p_din2 = 32'd1073741824;

assign grp_pow_generic_float_s_fu_2010_p_din1 = grp_fu_1960_p_dout0;

assign grp_pow_generic_float_s_fu_2010_p_din2 = 32'd1061158912;

assign icmp_ln59_fu_271_p2 = ((ap_sig_allocacmp_indvar_flatten19_load == 8'd169) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_295_p2 = ((ap_sig_allocacmp_y_load == 4'd13) ? 1'b1 : 1'b0);

assign inp_image_1_address0 = zext_ln67_2_reg_398_pp0_iter6_reg;

assign inp_image_1_ce0 = inp_image_1_ce0_local;

assign inp_image_2_address0 = zext_ln67_2_reg_398_pp0_iter10_reg;

assign inp_image_2_ce0 = inp_image_2_ce0_local;

assign inp_image_address0 = zext_ln67_2_fu_345_p1;

assign inp_image_ce0 = inp_image_ce0_local;

assign out_img_address0 = zext_ln67_2_reg_398_pp0_iter63_reg;

assign out_img_ce0 = out_img_ce0_local;

assign out_img_d0 = div_reg_491;

assign out_img_we0 = out_img_we0_local;

assign select_ln59_1_fu_309_p3 = ((icmp_ln62_fu_295_p2[0:0] == 1'b1) ? add_ln59_fu_289_p2 : ap_sig_allocacmp_x_load);

assign select_ln59_fu_301_p3 = ((icmp_ln62_fu_295_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_y_load);

assign zext_ln67_2_fu_345_p1 = grp_fu_349_p3;

always @ (posedge ap_clk) begin
    zext_ln67_2_reg_398[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter4_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter5_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter6_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter7_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter8_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter9_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter10_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter11_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter12_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter13_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter14_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter15_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter16_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter17_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter18_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter19_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter20_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter21_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter22_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter23_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter24_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter25_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter26_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter27_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter28_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter29_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter30_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter31_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter32_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter33_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter34_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter35_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter36_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter37_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter38_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter39_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter40_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter41_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter42_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter43_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter44_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter45_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter46_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter47_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter48_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter49_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter50_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter51_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter52_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter53_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter54_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter55_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter56_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter57_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter58_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter59_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter60_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter61_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter62_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln67_2_reg_398_pp0_iter63_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //NN_norm2_Pipeline_L2_L3
