-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity NN_pow_generic_float_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    base_r : IN STD_LOGIC_VECTOR (31 downto 0);
    exp : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of NN_pow_generic_float_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv52_B17217F7D1C : STD_LOGIC_VECTOR (51 downto 0) := "0000000010110001011100100001011111110111110100011100";
    constant ap_const_lv36_B17217F7D : STD_LOGIC_VECTOR (35 downto 0) := "101100010111001000010111111101111101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv9_16 : STD_LOGIC_VECTOR (8 downto 0) := "000010110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv23_7FFFFF : STD_LOGIC_VECTOR (22 downto 0) := "11111111111111111111111";
    constant ap_const_lv9_18 : STD_LOGIC_VECTOR (8 downto 0) := "000011000";
    constant ap_const_lv9_96 : STD_LOGIC_VECTOR (8 downto 0) := "010010110";
    constant ap_const_lv9_182 : STD_LOGIC_VECTOR (8 downto 0) := "110000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv15_4000 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv27_4 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000100";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv10_382 : STD_LOGIC_VECTOR (9 downto 0) := "1110000010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv31_3F800000 : STD_LOGIC_VECTOR (30 downto 0) := "0111111100000000000000000000000";
    constant ap_const_lv31_7F800000 : STD_LOGIC_VECTOR (30 downto 0) := "1111111100000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv32_7FFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "01111111111111111111111111111111";
    constant ap_const_lv25_B8A : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000101110001010";

attribute shreg_extract : string;
    signal pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal pow_reduce_anonymous_namespace_log0_lut_table_array_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal pow_reduce_anonymous_namespace_log0_lut_table_array_q0 : STD_LOGIC_VECTOR (55 downto 0);
    signal pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_q0 : STD_LOGIC_VECTOR (51 downto 0);
    signal pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_q0 : STD_LOGIC_VECTOR (48 downto 0);
    signal pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_q0 : STD_LOGIC_VECTOR (43 downto 0);
    signal pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_q0 : STD_LOGIC_VECTOR (26 downto 0);
    signal pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal exp_read_reg_2204 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exp_read_reg_2204_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_read_reg_2204_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_read_reg_2204_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal bs_exp_reg_2209 : STD_LOGIC_VECTOR (7 downto 0);
    signal bs_exp_reg_2209_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal bs_exp_reg_2209_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal bs_exp_reg_2209_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal bs_sig_fu_451_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal bs_sig_reg_2216 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_reg_2224 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_2224_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_2224_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_2224_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_2231 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_2231_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_2231_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_2231_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln340_1_fu_487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln340_1_reg_2247 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln340_1_reg_2247_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln340_1_reg_2247_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_4_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_4_reg_2253 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_4_reg_2253_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_4_reg_2253_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal log_sum_reg_2258 : STD_LOGIC_VECTOR (55 downto 0);
    signal log_sum_reg_2258_pp0_iter2_reg : STD_LOGIC_VECTOR (55 downto 0);
    signal a_fu_550_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_reg_2263 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln39_fu_560_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln39_reg_2268 : STD_LOGIC_VECTOR (20 downto 0);
    signal select_ln42_fu_608_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal select_ln42_reg_2273 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln44_fu_620_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal mul_ln44_reg_2278 : STD_LOGIC_VECTOR (42 downto 0);
    signal z3_reg_2288 : STD_LOGIC_VECTOR (43 downto 0);
    signal a_3_fu_762_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal a_3_reg_2299 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_7_reg_2304 : STD_LOGIC_VECTOR (37 downto 0);
    signal log_sum_1_fu_872_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal log_sum_1_reg_2314 : STD_LOGIC_VECTOR (55 downto 0);
    signal tmp_8_reg_2319 : STD_LOGIC_VECTOR (38 downto 0);
    signal zk_trunc_reg_2324 : STD_LOGIC_VECTOR (22 downto 0);
    signal es_exp_fu_909_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal es_exp_reg_2329 : STD_LOGIC_VECTOR (7 downto 0);
    signal m_exp_fu_934_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal m_exp_reg_2334 : STD_LOGIC_VECTOR (8 downto 0);
    signal x_is_n1_fu_968_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_n1_reg_2341 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_n1_reg_2341_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_n1_reg_2341_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_n1_reg_2341_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_n1_reg_2341_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_n1_reg_2341_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_n1_reg_2341_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_1046_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_2347 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_2347_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln378_1_fu_1144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln378_1_reg_2355 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln378_1_reg_2355_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln378_1_reg_2355_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln378_1_reg_2355_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln378_1_reg_2355_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln378_1_reg_2355_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln378_1_reg_2355_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln386_2_fu_1174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln386_2_reg_2362 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln386_2_reg_2362_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln386_2_reg_2362_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln386_2_reg_2362_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln386_2_reg_2362_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln386_2_reg_2362_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln386_2_reg_2362_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln422_fu_1218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln422_reg_2368 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln422_reg_2368_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln422_reg_2368_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln422_reg_2368_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln422_reg_2368_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln422_reg_2368_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_sign_fu_1294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_sign_reg_2373 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_sign_reg_2373_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_sign_reg_2373_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_sign_reg_2373_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_sign_reg_2373_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_sign_reg_2373_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_sign_reg_2373_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln431_2_fu_1336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln431_2_reg_2381 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln431_2_reg_2381_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln431_2_reg_2381_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln431_2_reg_2381_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln431_2_reg_2381_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln431_2_reg_2381_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln431_2_reg_2381_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln438_2_fu_1378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln438_2_reg_2387 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln438_2_reg_2387_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln438_2_reg_2387_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln438_2_reg_2387_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln438_2_reg_2387_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln438_2_reg_2387_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln438_2_reg_2387_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal log_base_reg_2393 : STD_LOGIC_VECTOR (42 downto 0);
    signal e_frac_2_fu_1503_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal e_frac_2_reg_2398 : STD_LOGIC_VECTOR (24 downto 0);
    signal m_frac_l_fu_431_p2 : STD_LOGIC_VECTOR (66 downto 0);
    signal m_frac_l_reg_2403 : STD_LOGIC_VECTOR (66 downto 0);
    signal select_ln545_fu_1528_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln545_reg_2410 : STD_LOGIC_VECTOR (8 downto 0);
    signal m_fix_reg_2415 : STD_LOGIC_VECTOR (26 downto 0);
    signal m_fix_reg_2415_pp0_iter6_reg : STD_LOGIC_VECTOR (26 downto 0);
    signal m_fix_reg_2415_pp0_iter7_reg : STD_LOGIC_VECTOR (26 downto 0);
    signal m_fix_reg_2415_pp0_iter8_reg : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_10_reg_2420 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_2420_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_2430 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_2430_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_2430_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_2430_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_2430_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_2430_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln628_fu_1704_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln628_reg_2436 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln628_reg_2436_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln628_reg_2436_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln628_reg_2436_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_exp_fu_1759_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_exp_reg_2446 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_exp_reg_2446_pp0_iter9_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal m_diff_lo_fu_1796_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal m_diff_lo_reg_2453 : STD_LOGIC_VECTOR (17 downto 0);
    signal or_ln628_fu_1931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln628_reg_2468 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln645_fu_1937_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln645_reg_2474 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_sig_fu_1963_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal out_sig_reg_2479 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln657_fu_1971_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln657_reg_2484 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln502_fu_481_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln46_fu_661_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_1_fu_757_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln46_2_fu_782_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln611_fu_1800_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln159_fu_1815_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_ce0_local : STD_LOGIC;
    signal pow_reduce_anonymous_namespace_log0_lut_table_array_ce0_local : STD_LOGIC;
    signal pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_ce0_local : STD_LOGIC;
    signal pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_ce0_local : STD_LOGIC;
    signal pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_ce0_local : STD_LOGIC;
    signal pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_ce0_local : STD_LOGIC;
    signal pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_ce0_local : STD_LOGIC;
    signal Elog2_fu_413_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal mul_ln522_fu_423_p0 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln522_fu_1402_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal mul_ln522_fu_423_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mul_ln44_1_fu_427_p0 : STD_LOGIC_VECTOR (40 downto 0);
    signal mul_ln44_1_fu_427_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln44_2_fu_435_p0 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln44_2_fu_435_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal data_fu_439_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal index0_fu_471_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal b_frac_1_fu_506_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln485_fu_513_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal b_frac_fu_497_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal b_frac_2_fu_517_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal b_frac1_fu_532_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal b_frac1_fu_532_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal b_frac1_fu_532_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln516_fu_538_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_s_fu_572_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal zext_ln42_fu_580_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal z1_fu_542_p3 : STD_LOGIC_VECTOR (38 downto 0);
    signal zext_ln42_1_fu_592_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal zext_ln42_2_cast_fu_584_p3 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_5_fu_564_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_596_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal zext_ln42_2_fu_604_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln44_fu_620_p0 : STD_LOGIC_VECTOR (38 downto 0);
    signal mul_ln44_fu_620_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln44_2_fu_626_p3 : STD_LOGIC_VECTOR (42 downto 0);
    signal zext_ln44_fu_633_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal add_ln44_fu_637_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal zext_ln44_2_fu_642_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal sub_ln44_fu_645_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal z2_fu_651_p4 : STD_LOGIC_VECTOR (40 downto 0);
    signal zext_ln40_fu_675_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_6_fu_687_p4 : STD_LOGIC_VECTOR (34 downto 0);
    signal shl_ln44_3_fu_697_p3 : STD_LOGIC_VECTOR (48 downto 0);
    signal eZ_fu_679_p3 : STD_LOGIC_VECTOR (48 downto 0);
    signal zext_ln44_3_fu_705_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal zext_ln44_4_fu_709_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal a_1_fu_665_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln44_1_fu_427_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal shl_ln_fu_729_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln44_1_fu_713_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal zext_ln44_7_fu_737_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal sub_ln44_1_fu_741_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal zext_ln40_1_fu_803_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal shl_ln44_4_fu_814_p3 : STD_LOGIC_VECTOR (61 downto 0);
    signal eZ_1_fu_806_p3 : STD_LOGIC_VECTOR (56 downto 0);
    signal zext_ln44_9_fu_821_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln44_10_fu_825_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal mul_ln44_2_fu_435_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal shl_ln44_1_fu_835_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal add_ln44_2_fu_829_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln44_11_fu_843_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln134_fu_787_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal zext_ln134_1_fu_795_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal zext_ln134_2_fu_853_p1 : STD_LOGIC_VECTOR (49 downto 0);
    signal add_ln142_1_fu_862_p2 : STD_LOGIC_VECTOR (49 downto 0);
    signal zext_ln142_fu_868_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal add_ln142_fu_857_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal sub_ln44_2_fu_847_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal data_1_fu_898_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln317_fu_921_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln317_1_fu_930_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal b_exp_fu_924_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln340_fu_946_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_1_fu_952_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln341_fu_957_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sig_fu_917_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln18_fu_973_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_1_fu_979_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_2_fu_991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_3_fu_1003_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_0_fu_1013_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_inf_fu_1018_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln357_fu_1023_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln357_fu_1029_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal es_exp_cast_fu_1054_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln373_fu_1064_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln373_fu_1070_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal lshr_ln373_fu_1074_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal and_ln373_1_fu_1080_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln372_fu_1040_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln373_fu_1092_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln373_fu_1098_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_int_fu_1112_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_int_fu_1112_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_int_fu_1112_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_is_inf_fu_985_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_p1_fu_962_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln378_fu_1132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln378_fu_1138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_0_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_int_fu_1112_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln386_fu_1150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_neg_fu_1035_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln386_fu_1156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_is_NaN_fu_1008_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln386_fu_1162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln386_1_fu_1168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_NaN_fu_997_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal es_sign_fu_901_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_pos_fu_1180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_1198_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln422_fu_1230_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal y_is_odd_fu_1240_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln421_fu_1212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln422_1_fu_1224_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln421_fu_1248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln422_fu_1254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln422_1_fu_1260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_odd_fu_1240_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_odd_1_fu_1274_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_odd_1_fu_1274_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_is_odd_1_fu_1274_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_pinf_fu_1186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_abs_greater_1_fu_1206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_ninf_fu_1192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln431_2_fu_1312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln431_fu_1300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln431_fu_1324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln431_3_fu_1318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln431_1_fu_1330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln431_1_fu_1306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln438_2_fu_1354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln438_1_fu_1348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln438_fu_1366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln438_3_fu_1360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln438_1_fu_1372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln438_fu_1342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal b_exp_1_fu_1384_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal b_exp_2_fu_1390_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln522_fu_423_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal lshr_ln_fu_1407_p4 : STD_LOGIC_VECTOR (43 downto 0);
    signal shl_ln1_fu_1417_p3 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln522_1_fu_1424_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal sub_ln522_fu_1428_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal Elog2_fu_413_p2 : STD_LOGIC_VECTOR (51 downto 0);
    signal shl_ln2_fu_1444_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln525_fu_1452_p1 : STD_LOGIC_VECTOR (64 downto 0);
    signal sext_ln525_1_fu_1456_p1 : STD_LOGIC_VECTOR (64 downto 0);
    signal lshr_ln522_1_fu_1434_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal add_ln525_fu_1459_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal zext_ln525_fu_1465_p1 : STD_LOGIC_VECTOR (64 downto 0);
    signal add_ln525_1_fu_1469_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal e_frac_fu_1485_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln532_fu_1493_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal e_frac_1_fu_1497_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal sub_ln545_fu_1519_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln545_fu_1524_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln552_fu_1534_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln552_fu_1537_p1 : STD_LOGIC_VECTOR (66 downto 0);
    signal tmp_9_fu_1547_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln553_fu_1555_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln553_fu_1562_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln553_fu_1566_p1 : STD_LOGIC_VECTOR (66 downto 0);
    signal shl_ln553_fu_1570_p2 : STD_LOGIC_VECTOR (66 downto 0);
    signal ashr_ln553_fu_1576_p2 : STD_LOGIC_VECTOR (66 downto 0);
    signal select_ln553_1_fu_1582_p3 : STD_LOGIC_VECTOR (66 downto 0);
    signal shl_ln552_fu_1541_p2 : STD_LOGIC_VECTOR (66 downto 0);
    signal m_fix_0_in_in_v_v_fu_1590_p3 : STD_LOGIC_VECTOR (66 downto 0);
    signal empty_fu_1597_p1 : STD_LOGIC_VECTOR (65 downto 0);
    signal zext_ln549_fu_1601_p1 : STD_LOGIC_VECTOR (66 downto 0);
    signal m_fix_hi_fu_1615_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln545_1_fu_1645_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln545_fu_1648_p1 : STD_LOGIC_VECTOR (66 downto 0);
    signal ashr_ln545_fu_1652_p2 : STD_LOGIC_VECTOR (66 downto 0);
    signal shl_ln545_fu_1657_p2 : STD_LOGIC_VECTOR (66 downto 0);
    signal trunc_ln545_fu_1662_p1 : STD_LOGIC_VECTOR (65 downto 0);
    signal trunc_ln545_1_fu_1666_p1 : STD_LOGIC_VECTOR (65 downto 0);
    signal m_fix_l_fu_1670_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal zext_ln546_fu_1677_p1 : STD_LOGIC_VECTOR (65 downto 0);
    signal shl_ln546_fu_1681_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal ashr_ln546_fu_1687_p2 : STD_LOGIC_VECTOR (65 downto 0);
    signal m_fix_back_fu_1693_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal sext_ln628_fu_1700_p1 : STD_LOGIC_VECTOR (66 downto 0);
    signal shl_ln3_fu_1709_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_2193_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln563_fu_1736_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_10_cast_fu_1720_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln563_fu_1739_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln563_1_fu_1745_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_13_fu_1729_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln563_fu_1751_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln568_fu_418_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal m_fix_a_fu_1771_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal sub_ln574_fu_1781_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal m_diff_hi_fu_1786_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal Z2_ind_fu_1805_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln160_fu_1820_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln160_1_fu_1823_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln160_fu_1827_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal exp_Z1_hi_fu_1843_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_Z1P_m_1_fu_1833_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln616_fu_1867_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln616_fu_1867_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln616_fu_1853_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln616_fu_1867_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal shl_ln4_fu_1873_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal zext_ln616_2_fu_1881_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal add_ln616_1_fu_1885_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_14_fu_1891_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_exp_1_fu_1899_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_exp_2_fu_1904_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_15_fu_1915_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln628_fu_1911_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln628_1_fu_1925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_1943_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_12_fu_1953_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal t_fu_1975_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_1_fu_1996_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_2_fu_2007_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_exp_fu_2018_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_3_fu_2023_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln386_3_fu_2035_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln386_1_fu_2039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln386_2_fu_2050_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln342_fu_2060_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln342_1_fu_2065_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln431_fu_1986_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln431_5_fu_2076_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln438_fu_1991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln438_5_fu_2087_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln628_1_fu_2093_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln629_fu_2103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln628_fu_2114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln645_fu_2119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln342_fu_2045_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln386_1_fu_2055_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln431_4_fu_2071_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln438_4_fu_2082_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln629_fu_2098_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln629_1_fu_2108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln645_1_fu_2124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_2_fu_2149_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln327_1_fu_2003_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln327_2_fu_2014_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_2_fu_2149_p18 : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_2_fu_2149_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal retval_2_fu_2149_p20 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_2193_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal retval_2_fu_2149_p21 : STD_LOGIC_VECTOR (31 downto 0);
    signal base_r_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal exp_int_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal b_frac1_fu_532_p00 : STD_LOGIC_VECTOR (30 downto 0);
    signal b_frac1_fu_532_p10 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln44_1_fu_427_p00 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln44_1_fu_427_p10 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln44_2_fu_435_p00 : STD_LOGIC_VECTOR (49 downto 0);
    signal mul_ln44_2_fu_435_p10 : STD_LOGIC_VECTOR (49 downto 0);
    signal mul_ln44_fu_620_p10 : STD_LOGIC_VECTOR (42 downto 0);
    signal mul_ln616_fu_1867_p00 : STD_LOGIC_VECTOR (35 downto 0);
    signal mul_ln616_fu_1867_p10 : STD_LOGIC_VECTOR (35 downto 0);
    signal y_is_int_fu_1112_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_is_int_fu_1112_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_is_int_fu_1112_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_is_odd_fu_1240_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_is_odd_1_fu_1274_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_is_odd_1_fu_1274_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_is_odd_1_fu_1274_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal retval_2_fu_2149_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_2_fu_2149_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_2_fu_2149_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_2_fu_2149_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_2_fu_2149_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_2_fu_2149_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_2_fu_2149_p13 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_2_fu_2149_p15 : STD_LOGIC_VECTOR (7 downto 0);
    signal retval_2_fu_2149_p17 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component NN_mul_9s_45ns_52_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (44 downto 0);
        dout : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component NN_mul_10s_36s_36_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (35 downto 0);
        dout : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;


    component NN_mul_23ns_23ns_45_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (22 downto 0);
        din1 : IN STD_LOGIC_VECTOR (22 downto 0);
        dout : OUT STD_LOGIC_VECTOR (44 downto 0) );
    end component;


    component NN_mul_41ns_6ns_47_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (40 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (46 downto 0) );
    end component;


    component NN_mul_43s_25s_67_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (42 downto 0);
        din1 : IN STD_LOGIC_VECTOR (24 downto 0);
        dout : OUT STD_LOGIC_VECTOR (66 downto 0) );
    end component;


    component NN_mul_44ns_6ns_50_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (43 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (49 downto 0) );
    end component;


    component NN_mul_25ns_6ns_31_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (24 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component NN_mul_39ns_4ns_43_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (38 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (42 downto 0) );
    end component;


    component NN_sparsemux_7_2_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component NN_bitselect_1ns_23ns_32s_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (22 downto 0);
        sel : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component NN_mul_18ns_18ns_36_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        dout : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;


    component NN_sparsemux_19_8_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (7 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (7 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (7 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (7 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (7 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (7 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (7 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (7 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (7 downto 0);
        din8_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component NN_mac_muladd_13s_12ns_16s_25_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (12 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_log0_lut_table_array_ROM_Acud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (55 downto 0) );
    end component;


    component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4dEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (51 downto 0) );
    end component;


    component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6eOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (48 downto 0) );
    end component;


    component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_fYi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (43 downto 0) );
    end component;


    component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_arrg8j IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;


    component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_arrayhbi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_U : component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_bkb
    generic map (
        DataWidth => 6,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_address0,
        ce0 => pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_ce0_local,
        q0 => pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_q0);

    pow_reduce_anonymous_namespace_log0_lut_table_array_U : component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_log0_lut_table_array_ROM_Acud
    generic map (
        DataWidth => 56,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pow_reduce_anonymous_namespace_log0_lut_table_array_address0,
        ce0 => pow_reduce_anonymous_namespace_log0_lut_table_array_ce0_local,
        q0 => pow_reduce_anonymous_namespace_log0_lut_table_array_q0);

    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_U : component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4dEe
    generic map (
        DataWidth => 52,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_address0,
        ce0 => pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_ce0_local,
        q0 => pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_q0);

    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_U : component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6eOg
    generic map (
        DataWidth => 49,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_address0,
        ce0 => pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_ce0_local,
        q0 => pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_q0);

    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_U : component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_fYi
    generic map (
        DataWidth => 44,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_address0,
        ce0 => pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_ce0_local,
        q0 => pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_q0);

    pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_U : component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_arrg8j
    generic map (
        DataWidth => 27,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_address0,
        ce0 => pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_ce0_local,
        q0 => pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_q0);

    pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_U : component NN_pow_generic_float_s_pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_arrayhbi
    generic map (
        DataWidth => 8,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_address0,
        ce0 => pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_ce0_local,
        q0 => pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_q0);

    mul_9s_45ns_52_1_1_U3087 : component NN_mul_9s_45ns_52_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 45,
        dout_WIDTH => 52)
    port map (
        din0 => b_exp_2_fu_1390_p3,
        din1 => Elog2_fu_413_p1,
        dout => Elog2_fu_413_p2);

    mul_10s_36s_36_1_1_U3088 : component NN_mul_10s_36s_36_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 36,
        dout_WIDTH => 36)
    port map (
        din0 => r_exp_reg_2446,
        din1 => ap_const_lv36_B17217F7D,
        dout => mul_ln568_fu_418_p2);

    mul_23ns_23ns_45_1_1_U3089 : component NN_mul_23ns_23ns_45_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 23,
        din1_WIDTH => 23,
        dout_WIDTH => 45)
    port map (
        din0 => mul_ln522_fu_423_p0,
        din1 => mul_ln522_fu_423_p1,
        dout => mul_ln522_fu_423_p2);

    mul_41ns_6ns_47_1_1_U3090 : component NN_mul_41ns_6ns_47_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 41,
        din1_WIDTH => 6,
        dout_WIDTH => 47)
    port map (
        din0 => mul_ln44_1_fu_427_p0,
        din1 => mul_ln44_1_fu_427_p1,
        dout => mul_ln44_1_fu_427_p2);

    mul_43s_25s_67_1_1_U3091 : component NN_mul_43s_25s_67_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 43,
        din1_WIDTH => 25,
        dout_WIDTH => 67)
    port map (
        din0 => log_base_reg_2393,
        din1 => e_frac_2_reg_2398,
        dout => m_frac_l_fu_431_p2);

    mul_44ns_6ns_50_1_1_U3092 : component NN_mul_44ns_6ns_50_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 44,
        din1_WIDTH => 6,
        dout_WIDTH => 50)
    port map (
        din0 => mul_ln44_2_fu_435_p0,
        din1 => mul_ln44_2_fu_435_p1,
        dout => mul_ln44_2_fu_435_p2);

    mul_25ns_6ns_31_1_1_U3093 : component NN_mul_25ns_6ns_31_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 6,
        dout_WIDTH => 31)
    port map (
        din0 => b_frac1_fu_532_p0,
        din1 => b_frac1_fu_532_p1,
        dout => b_frac1_fu_532_p2);

    mul_39ns_4ns_43_1_1_U3094 : component NN_mul_39ns_4ns_43_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 39,
        din1_WIDTH => 4,
        dout_WIDTH => 43)
    port map (
        din0 => mul_ln44_fu_620_p0,
        din1 => mul_ln44_fu_620_p1,
        dout => mul_ln44_fu_620_p2);

    sparsemux_7_2_1_1_1_U3095 : component NN_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "00",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_1,
        din1 => y_is_int_fu_1112_p4,
        din2 => ap_const_lv1_0,
        def => y_is_int_fu_1112_p7,
        sel => y_is_int_fu_1112_p8,
        dout => y_is_int_fu_1112_p9);

    bitselect_1ns_23ns_32s_1_1_1_U3096 : component NN_bitselect_1ns_23ns_32s_1_1_1
    generic map (
        DATAWIDTH => 23,
        ADDRWIDTH => 32)
    port map (
        din => es_sig_fu_917_p1,
        sel => y_is_odd_fu_1240_p2,
        dout => y_is_odd_fu_1240_p3);

    sparsemux_7_2_1_1_1_U3097 : component NN_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "00",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => ap_const_lv1_1,
        din1 => y_is_odd_fu_1240_p3,
        din2 => ap_const_lv1_0,
        def => y_is_odd_1_fu_1274_p7,
        sel => y_is_odd_1_fu_1274_p8,
        dout => y_is_odd_1_fu_1274_p9);

    mul_18ns_18ns_36_1_1_U3098 : component NN_mul_18ns_18ns_36_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 18,
        din1_WIDTH => 18,
        dout_WIDTH => 36)
    port map (
        din0 => mul_ln616_fu_1867_p0,
        din1 => mul_ln616_fu_1867_p1,
        dout => mul_ln616_fu_1867_p2);

    sparsemux_19_8_32_1_1_U3099 : component NN_sparsemux_19_8_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10000000",
        din0_WIDTH => 32,
        CASE1 => "01000000",
        din1_WIDTH => 32,
        CASE2 => "00100000",
        din2_WIDTH => 32,
        CASE3 => "00010000",
        din3_WIDTH => 32,
        CASE4 => "00001000",
        din4_WIDTH => 32,
        CASE5 => "00000100",
        din5_WIDTH => 32,
        CASE6 => "00000010",
        din6_WIDTH => 32,
        CASE7 => "00000001",
        din7_WIDTH => 32,
        CASE8 => "00000000",
        din8_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_3F800000,
        din1 => retval_2_fu_2149_p4,
        din2 => ap_const_lv32_7FFFFFFF,
        din3 => bitcast_ln327_1_fu_2003_p1,
        din4 => bitcast_ln327_2_fu_2014_p1,
        din5 => bitcast_ln327_2_fu_2014_p1,
        din6 => bitcast_ln327_1_fu_2003_p1,
        din7 => bitcast_ln327_2_fu_2014_p1,
        din8 => retval_2_fu_2149_p18,
        def => retval_2_fu_2149_p19,
        sel => retval_2_fu_2149_p20,
        dout => retval_2_fu_2149_p21);

    mac_muladd_13s_12ns_16s_25_4_1_U3100 : component NN_mac_muladd_13s_12ns_16s_25_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 13,
        din1_WIDTH => 12,
        din2_WIDTH => 16,
        dout_WIDTH => 25)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => m_fix_hi_fu_1615_p4,
        din1 => grp_fu_2193_p1,
        din2 => shl_ln3_fu_1709_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_2193_p3);





    base_r_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            base_r_int_reg <= base_r;
        end if;
    end process;

    exp_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            exp_int_reg <= exp;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                a_3_reg_2299 <= sub_ln44_1_fu_741_p2(49 downto 44);
                a_reg_2263 <= b_frac1_fu_532_p2(24 downto 21);
                bs_exp_reg_2209 <= data_fu_439_p1(30 downto 23);
                bs_exp_reg_2209_pp0_iter1_reg <= bs_exp_reg_2209;
                bs_exp_reg_2209_pp0_iter2_reg <= bs_exp_reg_2209_pp0_iter1_reg;
                bs_exp_reg_2209_pp0_iter3_reg <= bs_exp_reg_2209_pp0_iter2_reg;
                bs_sig_reg_2216 <= bs_sig_fu_451_p1;
                e_frac_2_reg_2398 <= e_frac_2_fu_1503_p3;
                es_exp_reg_2329 <= data_1_fu_898_p1(30 downto 23);
                exp_read_reg_2204 <= exp_int_reg;
                exp_read_reg_2204_pp0_iter1_reg <= exp_read_reg_2204;
                exp_read_reg_2204_pp0_iter2_reg <= exp_read_reg_2204_pp0_iter1_reg;
                exp_read_reg_2204_pp0_iter3_reg <= exp_read_reg_2204_pp0_iter2_reg;
                icmp_ln18_4_reg_2253 <= icmp_ln18_4_fu_492_p2;
                icmp_ln18_4_reg_2253_pp0_iter2_reg <= icmp_ln18_4_reg_2253;
                icmp_ln18_4_reg_2253_pp0_iter3_reg <= icmp_ln18_4_reg_2253_pp0_iter2_reg;
                icmp_ln340_1_reg_2247 <= icmp_ln340_1_fu_487_p2;
                icmp_ln340_1_reg_2247_pp0_iter2_reg <= icmp_ln340_1_reg_2247;
                icmp_ln340_1_reg_2247_pp0_iter3_reg <= icmp_ln340_1_reg_2247_pp0_iter2_reg;
                icmp_ln422_reg_2368 <= icmp_ln422_fu_1218_p2;
                icmp_ln422_reg_2368_pp0_iter5_reg <= icmp_ln422_reg_2368;
                icmp_ln422_reg_2368_pp0_iter6_reg <= icmp_ln422_reg_2368_pp0_iter5_reg;
                icmp_ln422_reg_2368_pp0_iter7_reg <= icmp_ln422_reg_2368_pp0_iter6_reg;
                icmp_ln422_reg_2368_pp0_iter8_reg <= icmp_ln422_reg_2368_pp0_iter7_reg;
                icmp_ln422_reg_2368_pp0_iter9_reg <= icmp_ln422_reg_2368_pp0_iter8_reg;
                icmp_ln628_reg_2436 <= icmp_ln628_fu_1704_p2;
                icmp_ln628_reg_2436_pp0_iter7_reg <= icmp_ln628_reg_2436;
                icmp_ln628_reg_2436_pp0_iter8_reg <= icmp_ln628_reg_2436_pp0_iter7_reg;
                icmp_ln628_reg_2436_pp0_iter9_reg <= icmp_ln628_reg_2436_pp0_iter8_reg;
                icmp_ln645_reg_2474 <= icmp_ln645_fu_1937_p2;
                log_base_reg_2393 <= add_ln525_1_fu_1469_p2(64 downto 22);
                log_sum_1_reg_2314 <= log_sum_1_fu_872_p2;
                log_sum_reg_2258 <= pow_reduce_anonymous_namespace_log0_lut_table_array_q0;
                log_sum_reg_2258_pp0_iter2_reg <= log_sum_reg_2258;
                m_diff_lo_reg_2453 <= m_diff_lo_fu_1796_p1;
                m_exp_reg_2334 <= m_exp_fu_934_p2;
                m_fix_reg_2415 <= m_fix_0_in_in_v_v_fu_1590_p3(56 downto 30);
                m_fix_reg_2415_pp0_iter6_reg <= m_fix_reg_2415;
                m_fix_reg_2415_pp0_iter7_reg <= m_fix_reg_2415_pp0_iter6_reg;
                m_fix_reg_2415_pp0_iter8_reg <= m_fix_reg_2415_pp0_iter7_reg;
                m_frac_l_reg_2403 <= m_frac_l_fu_431_p2;
                mul_ln44_reg_2278 <= mul_ln44_fu_620_p2;
                or_ln378_1_reg_2355 <= or_ln378_1_fu_1144_p2;
                or_ln378_1_reg_2355_pp0_iter10_reg <= or_ln378_1_reg_2355_pp0_iter9_reg;
                or_ln378_1_reg_2355_pp0_iter5_reg <= or_ln378_1_reg_2355;
                or_ln378_1_reg_2355_pp0_iter6_reg <= or_ln378_1_reg_2355_pp0_iter5_reg;
                or_ln378_1_reg_2355_pp0_iter7_reg <= or_ln378_1_reg_2355_pp0_iter6_reg;
                or_ln378_1_reg_2355_pp0_iter8_reg <= or_ln378_1_reg_2355_pp0_iter7_reg;
                or_ln378_1_reg_2355_pp0_iter9_reg <= or_ln378_1_reg_2355_pp0_iter8_reg;
                or_ln386_2_reg_2362 <= or_ln386_2_fu_1174_p2;
                or_ln386_2_reg_2362_pp0_iter10_reg <= or_ln386_2_reg_2362_pp0_iter9_reg;
                or_ln386_2_reg_2362_pp0_iter5_reg <= or_ln386_2_reg_2362;
                or_ln386_2_reg_2362_pp0_iter6_reg <= or_ln386_2_reg_2362_pp0_iter5_reg;
                or_ln386_2_reg_2362_pp0_iter7_reg <= or_ln386_2_reg_2362_pp0_iter6_reg;
                or_ln386_2_reg_2362_pp0_iter8_reg <= or_ln386_2_reg_2362_pp0_iter7_reg;
                or_ln386_2_reg_2362_pp0_iter9_reg <= or_ln386_2_reg_2362_pp0_iter8_reg;
                or_ln431_2_reg_2381 <= or_ln431_2_fu_1336_p2;
                or_ln431_2_reg_2381_pp0_iter10_reg <= or_ln431_2_reg_2381_pp0_iter9_reg;
                or_ln431_2_reg_2381_pp0_iter5_reg <= or_ln431_2_reg_2381;
                or_ln431_2_reg_2381_pp0_iter6_reg <= or_ln431_2_reg_2381_pp0_iter5_reg;
                or_ln431_2_reg_2381_pp0_iter7_reg <= or_ln431_2_reg_2381_pp0_iter6_reg;
                or_ln431_2_reg_2381_pp0_iter8_reg <= or_ln431_2_reg_2381_pp0_iter7_reg;
                or_ln431_2_reg_2381_pp0_iter9_reg <= or_ln431_2_reg_2381_pp0_iter8_reg;
                or_ln438_2_reg_2387 <= or_ln438_2_fu_1378_p2;
                or_ln438_2_reg_2387_pp0_iter10_reg <= or_ln438_2_reg_2387_pp0_iter9_reg;
                or_ln438_2_reg_2387_pp0_iter5_reg <= or_ln438_2_reg_2387;
                or_ln438_2_reg_2387_pp0_iter6_reg <= or_ln438_2_reg_2387_pp0_iter5_reg;
                or_ln438_2_reg_2387_pp0_iter7_reg <= or_ln438_2_reg_2387_pp0_iter6_reg;
                or_ln438_2_reg_2387_pp0_iter8_reg <= or_ln438_2_reg_2387_pp0_iter7_reg;
                or_ln438_2_reg_2387_pp0_iter9_reg <= or_ln438_2_reg_2387_pp0_iter8_reg;
                or_ln628_reg_2468 <= or_ln628_fu_1931_p2;
                out_sig_reg_2479 <= out_sig_fu_1963_p3;
                r_exp_reg_2446 <= r_exp_fu_1759_p3;
                r_exp_reg_2446_pp0_iter9_reg <= r_exp_reg_2446;
                r_sign_reg_2373 <= r_sign_fu_1294_p2;
                r_sign_reg_2373_pp0_iter10_reg <= r_sign_reg_2373_pp0_iter9_reg;
                r_sign_reg_2373_pp0_iter5_reg <= r_sign_reg_2373;
                r_sign_reg_2373_pp0_iter6_reg <= r_sign_reg_2373_pp0_iter5_reg;
                r_sign_reg_2373_pp0_iter7_reg <= r_sign_reg_2373_pp0_iter6_reg;
                r_sign_reg_2373_pp0_iter8_reg <= r_sign_reg_2373_pp0_iter7_reg;
                r_sign_reg_2373_pp0_iter9_reg <= r_sign_reg_2373_pp0_iter8_reg;
                    select_ln42_reg_2273(38 downto 13) <= select_ln42_fu_608_p3(38 downto 13);    select_ln42_reg_2273(43 downto 42) <= select_ln42_fu_608_p3(43 downto 42);
                select_ln545_reg_2410 <= select_ln545_fu_1528_p3;
                tmp_10_reg_2420 <= zext_ln549_fu_1601_p1(65 downto 65);
                tmp_10_reg_2420_pp0_iter6_reg <= tmp_10_reg_2420;
                tmp_16_reg_2430 <= m_frac_l_fu_431_p2(66 downto 66);
                tmp_16_reg_2430_pp0_iter10_reg <= tmp_16_reg_2430_pp0_iter9_reg;
                tmp_16_reg_2430_pp0_iter6_reg <= tmp_16_reg_2430;
                tmp_16_reg_2430_pp0_iter7_reg <= tmp_16_reg_2430_pp0_iter6_reg;
                tmp_16_reg_2430_pp0_iter8_reg <= tmp_16_reg_2430_pp0_iter7_reg;
                tmp_16_reg_2430_pp0_iter9_reg <= tmp_16_reg_2430_pp0_iter8_reg;
                tmp_1_reg_2347 <= m_exp_fu_934_p2(8 downto 8);
                tmp_1_reg_2347_pp0_iter5_reg <= tmp_1_reg_2347;
                tmp_4_reg_2231 <= data_fu_439_p1(22 downto 22);
                tmp_4_reg_2231_pp0_iter1_reg <= tmp_4_reg_2231;
                tmp_4_reg_2231_pp0_iter2_reg <= tmp_4_reg_2231_pp0_iter1_reg;
                tmp_4_reg_2231_pp0_iter3_reg <= tmp_4_reg_2231_pp0_iter2_reg;
                tmp_7_reg_2304 <= sub_ln44_1_fu_741_p2(43 downto 6);
                tmp_8_reg_2319 <= sub_ln44_2_fu_847_p2(62 downto 24);
                tmp_reg_2224 <= data_fu_439_p1(31 downto 31);
                tmp_reg_2224_pp0_iter1_reg <= tmp_reg_2224;
                tmp_reg_2224_pp0_iter2_reg <= tmp_reg_2224_pp0_iter1_reg;
                tmp_reg_2224_pp0_iter3_reg <= tmp_reg_2224_pp0_iter2_reg;
                trunc_ln39_reg_2268 <= trunc_ln39_fu_560_p1;
                trunc_ln657_reg_2484 <= trunc_ln657_fu_1971_p1;
                x_is_n1_reg_2341 <= x_is_n1_fu_968_p2;
                x_is_n1_reg_2341_pp0_iter10_reg <= x_is_n1_reg_2341_pp0_iter9_reg;
                x_is_n1_reg_2341_pp0_iter5_reg <= x_is_n1_reg_2341;
                x_is_n1_reg_2341_pp0_iter6_reg <= x_is_n1_reg_2341_pp0_iter5_reg;
                x_is_n1_reg_2341_pp0_iter7_reg <= x_is_n1_reg_2341_pp0_iter6_reg;
                x_is_n1_reg_2341_pp0_iter8_reg <= x_is_n1_reg_2341_pp0_iter7_reg;
                x_is_n1_reg_2341_pp0_iter9_reg <= x_is_n1_reg_2341_pp0_iter8_reg;
                z3_reg_2288 <= sub_ln44_1_fu_741_p2(49 downto 6);
                zk_trunc_reg_2324 <= sub_ln44_2_fu_847_p2(62 downto 40);
            end if;
        end if;
    end process;
    select_ln42_reg_2273(12 downto 0) <= "0000000000000";
    select_ln42_reg_2273(41 downto 39) <= "000";
    Elog2_fu_413_p1 <= ap_const_lv52_B17217F7D1C(45 - 1 downto 0);
    Z2_ind_fu_1805_p4 <= sub_ln574_fu_1781_p2(17 downto 13);
    a_1_fu_665_p4 <= sub_ln44_fu_645_p2(43 downto 38);
    a_3_fu_762_p4 <= sub_ln44_1_fu_741_p2(49 downto 44);
    a_fu_550_p4 <= b_frac1_fu_532_p2(24 downto 21);
    add_ln142_1_fu_862_p2 <= std_logic_vector(unsigned(zext_ln134_1_fu_795_p1) + unsigned(zext_ln134_2_fu_853_p1));
    add_ln142_fu_857_p2 <= std_logic_vector(unsigned(zext_ln134_fu_787_p1) + unsigned(log_sum_reg_2258_pp0_iter2_reg));
    add_ln160_fu_1827_p2 <= std_logic_vector(unsigned(zext_ln160_fu_1820_p1) + unsigned(zext_ln160_1_fu_1823_p1));
    add_ln373_fu_1064_p2 <= std_logic_vector(unsigned(es_exp_cast_fu_1054_p4) + unsigned(ap_const_lv5_1));
    add_ln44_1_fu_713_p2 <= std_logic_vector(unsigned(zext_ln44_3_fu_705_p1) + unsigned(zext_ln44_4_fu_709_p1));
    add_ln44_2_fu_829_p2 <= std_logic_vector(unsigned(zext_ln44_9_fu_821_p1) + unsigned(zext_ln44_10_fu_825_p1));
    add_ln44_fu_637_p2 <= std_logic_vector(unsigned(zext_ln44_fu_633_p1) + unsigned(select_ln42_reg_2273));
    add_ln525_1_fu_1469_p2 <= std_logic_vector(unsigned(add_ln525_fu_1459_p2) + unsigned(zext_ln525_fu_1465_p1));
    add_ln525_fu_1459_p2 <= std_logic_vector(signed(sext_ln525_fu_1452_p1) + signed(sext_ln525_1_fu_1456_p1));
    add_ln563_1_fu_1745_p2 <= std_logic_vector(unsigned(tmp_10_cast_fu_1720_p4) + unsigned(ap_const_lv10_1));
    add_ln616_1_fu_1885_p2 <= std_logic_vector(unsigned(shl_ln4_fu_1873_p3) + unsigned(zext_ln616_2_fu_1881_p1));
    add_ln616_fu_1853_p2 <= std_logic_vector(unsigned(pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_q0) + unsigned(ap_const_lv27_4));
    and_ln342_1_fu_2065_p2 <= (xor_ln386_1_fu_2039_p2 and xor_ln342_fu_2060_p2);
    and_ln342_fu_2045_p2 <= (xor_ln386_1_fu_2039_p2 and x_is_n1_reg_2341_pp0_iter10_reg);
    and_ln373_1_fu_1080_p2 <= (lshr_ln373_fu_1074_p2 and es_sig_fu_917_p1);
    and_ln378_fu_1132_p2 <= (y_is_inf_fu_985_p2 and x_is_n1_fu_968_p2);
    and_ln386_1_fu_2055_p2 <= (xor_ln386_2_fu_2050_p2 and or_ln386_2_reg_2362_pp0_iter10_reg);
    and_ln386_fu_1162_p2 <= (xor_ln386_fu_1156_p2 and x_is_neg_fu_1035_p2);
    and_ln422_1_fu_1260_p2 <= (icmp_ln422_fu_1218_p2 and and_ln422_fu_1254_p2);
    and_ln422_fu_1254_p2 <= (xor_ln421_fu_1248_p2 and icmp_ln422_1_fu_1224_p2);
    and_ln431_1_fu_1306_p2 <= (y_is_ninf_fu_1192_p2 and tmp_2_fu_1198_p3);
    and_ln431_2_fu_1312_p2 <= (y_is_pos_fu_1180_p2 and x_is_inf_fu_1018_p2);
    and_ln431_3_fu_1318_p2 <= (x_is_0_fu_1013_p2 and es_sign_fu_901_p3);
    and_ln431_4_fu_2071_p2 <= (or_ln431_2_reg_2381_pp0_iter10_reg and and_ln342_1_fu_2065_p2);
    and_ln431_5_fu_2076_p2 <= (xor_ln431_fu_1986_p2 and and_ln342_1_fu_2065_p2);
    and_ln431_fu_1300_p2 <= (y_is_pinf_fu_1186_p2 and x_abs_greater_1_fu_1206_p2);
    and_ln438_1_fu_1348_p2 <= (y_is_ninf_fu_1192_p2 and x_abs_greater_1_fu_1206_p2);
    and_ln438_2_fu_1354_p2 <= (y_is_pos_fu_1180_p2 and x_is_0_fu_1013_p2);
    and_ln438_3_fu_1360_p2 <= (x_is_inf_fu_1018_p2 and es_sign_fu_901_p3);
    and_ln438_4_fu_2082_p2 <= (or_ln438_2_reg_2387_pp0_iter10_reg and and_ln431_5_fu_2076_p2);
    and_ln438_5_fu_2087_p2 <= (xor_ln438_fu_1991_p2 and and_ln431_5_fu_2076_p2);
    and_ln438_fu_1342_p2 <= (y_is_pinf_fu_1186_p2 and tmp_2_fu_1198_p3);
    and_ln628_1_fu_2093_p2 <= (or_ln628_reg_2468 and and_ln438_5_fu_2087_p2);
    and_ln628_fu_1911_p2 <= (icmp_ln628_reg_2436_pp0_iter9_reg and icmp_ln422_reg_2368_pp0_iter9_reg);
    and_ln629_1_fu_2108_p2 <= (xor_ln629_fu_2103_p2 and and_ln628_1_fu_2093_p2);
    and_ln629_fu_2098_p2 <= (tmp_16_reg_2430_pp0_iter10_reg and and_ln628_1_fu_2093_p2);
    and_ln645_1_fu_2124_p2 <= (and_ln645_fu_2119_p2 and and_ln438_5_fu_2087_p2);
    and_ln645_fu_2119_p2 <= (xor_ln628_fu_2114_p2 and icmp_ln645_reg_2474);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= retval_2_fu_2149_p21;
    ashr_ln545_fu_1652_p2 <= std_logic_vector(shift_right(signed(m_frac_l_reg_2403),to_integer(unsigned('0' & zext_ln545_fu_1648_p1(31-1 downto 0)))));
    ashr_ln546_fu_1687_p2 <= std_logic_vector(shift_right(signed(m_fix_l_fu_1670_p3),to_integer(unsigned('0' & zext_ln546_fu_1677_p1(31-1 downto 0)))));
    ashr_ln553_fu_1576_p2 <= std_logic_vector(shift_right(signed(m_frac_l_fu_431_p2),to_integer(unsigned('0' & zext_ln553_fu_1566_p1(31-1 downto 0)))));
    b_exp_1_fu_1384_p2 <= std_logic_vector(unsigned(zext_ln317_fu_921_p1) + unsigned(ap_const_lv9_182));
    b_exp_2_fu_1390_p3 <= 
        b_exp_1_fu_1384_p2 when (tmp_4_reg_2231_pp0_iter3_reg(0) = '1') else 
        b_exp_fu_924_p2;
    b_exp_fu_924_p2 <= std_logic_vector(unsigned(zext_ln317_fu_921_p1) + unsigned(ap_const_lv9_181));
    b_frac1_fu_532_p0 <= b_frac1_fu_532_p00(25 - 1 downto 0);
    b_frac1_fu_532_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_frac_2_fu_517_p3),31));
    b_frac1_fu_532_p1 <= b_frac1_fu_532_p10(6 - 1 downto 0);
    b_frac1_fu_532_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_q0),31));
    b_frac_1_fu_506_p3 <= (ap_const_lv1_1 & bs_sig_reg_2216);
    b_frac_2_fu_517_p3 <= 
        zext_ln485_fu_513_p1 when (tmp_4_reg_2231(0) = '1') else 
        b_frac_fu_497_p4;
    b_frac_fu_497_p4 <= ((ap_const_lv1_1 & bs_sig_reg_2216) & ap_const_lv1_0);
    bitcast_ln327_1_fu_2003_p1 <= t_1_fu_1996_p3;
    bitcast_ln327_2_fu_2014_p1 <= t_2_fu_2007_p3;
    bs_sig_fu_451_p1 <= data_fu_439_p1(23 - 1 downto 0);
    data_1_fu_898_p1 <= exp_read_reg_2204_pp0_iter3_reg;
    data_fu_439_p1 <= base_r_int_reg;
    eZ_1_fu_806_p3 <= (ap_const_lv1_1 & zext_ln40_1_fu_803_p1);
    eZ_fu_679_p3 <= (ap_const_lv1_1 & zext_ln40_fu_675_p1);
    e_frac_1_fu_1497_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(zext_ln532_fu_1493_p1));
    e_frac_2_fu_1503_p3 <= 
        e_frac_1_fu_1497_p2 when (es_sign_fu_901_p3(0) = '1') else 
        zext_ln532_fu_1493_p1;
    e_frac_fu_1485_p3 <= (ap_const_lv1_1 & es_sig_fu_917_p1);
    empty_fu_1597_p1 <= m_fix_0_in_in_v_v_fu_1590_p3(66 - 1 downto 0);
    es_exp_cast_fu_1054_p4 <= data_1_fu_898_p1(27 downto 23);
    es_exp_fu_909_p3 <= data_1_fu_898_p1(30 downto 23);
    es_sig_fu_917_p1 <= data_1_fu_898_p1(23 - 1 downto 0);
    es_sign_fu_901_p3 <= data_1_fu_898_p1(31 downto 31);
    exp_Z1P_m_1_fu_1833_p4 <= add_ln160_fu_1827_p2(18 downto 1);
    exp_Z1_hi_fu_1843_p4 <= pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_q0(26 downto 9);
    grp_fu_2193_p1 <= ap_const_lv25_B8A(12 - 1 downto 0);
    icmp_ln18_1_fu_979_p2 <= "1" when (es_sig_fu_917_p1 = ap_const_lv23_0) else "0";
    icmp_ln18_2_fu_991_p2 <= "0" when (es_sig_fu_917_p1 = ap_const_lv23_0) else "1";
    icmp_ln18_3_fu_1003_p2 <= "1" when (bs_exp_reg_2209_pp0_iter3_reg = ap_const_lv8_FF) else "0";
    icmp_ln18_4_fu_492_p2 <= "0" when (bs_sig_reg_2216 = ap_const_lv23_0) else "1";
    icmp_ln18_fu_973_p2 <= "1" when (es_exp_fu_909_p3 = ap_const_lv8_FF) else "0";
    icmp_ln340_1_fu_487_p2 <= "1" when (bs_sig_reg_2216 = ap_const_lv23_0) else "0";
    icmp_ln340_fu_946_p2 <= "1" when (b_exp_fu_924_p2 = ap_const_lv9_0) else "0";
    icmp_ln372_fu_1040_p2 <= "1" when (signed(m_exp_fu_934_p2) > signed(ap_const_lv9_16)) else "0";
    icmp_ln421_fu_1212_p2 <= "1" when (m_exp_fu_934_p2 = ap_const_lv9_0) else "0";
    icmp_ln422_1_fu_1224_p2 <= "1" when (signed(m_exp_fu_934_p2) < signed(ap_const_lv9_18)) else "0";
    icmp_ln422_fu_1218_p2 <= "1" when (signed(m_exp_fu_934_p2) > signed(ap_const_lv9_0)) else "0";
    icmp_ln563_fu_1739_p2 <= "0" when (trunc_ln563_fu_1736_p1 = ap_const_lv15_0) else "1";
    icmp_ln628_1_fu_1925_p2 <= "1" when (signed(tmp_15_fu_1915_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln628_fu_1704_p2 <= "0" when (m_frac_l_reg_2403 = sext_ln628_fu_1700_p1) else "1";
    icmp_ln645_fu_1937_p2 <= "1" when (signed(r_exp_2_fu_1904_p3) < signed(ap_const_lv10_382)) else "0";
    index0_fu_471_p4 <= data_fu_439_p1(22 downto 17);
    log_sum_1_fu_872_p2 <= std_logic_vector(unsigned(zext_ln142_fu_868_p1) + unsigned(add_ln142_fu_857_p2));
    lshr_ln373_fu_1074_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv23_7FFFFF),to_integer(unsigned('0' & zext_ln373_fu_1070_p1(23-1 downto 0)))));
    lshr_ln522_1_fu_1434_p4 <= sub_ln522_fu_1428_p2(62 downto 24);
    lshr_ln_fu_1407_p4 <= mul_ln522_fu_423_p2(44 downto 1);
    m_diff_hi_fu_1786_p4 <= sub_ln574_fu_1781_p2(26 downto 18);
    m_diff_lo_fu_1796_p1 <= sub_ln574_fu_1781_p2(18 - 1 downto 0);
    m_exp_fu_934_p2 <= std_logic_vector(unsigned(zext_ln317_1_fu_930_p1) + unsigned(ap_const_lv9_181));
    m_fix_0_in_in_v_v_fu_1590_p3 <= 
        select_ln553_1_fu_1582_p3 when (tmp_1_reg_2347(0) = '1') else 
        shl_ln552_fu_1541_p2;
    m_fix_a_fu_1771_p4 <= mul_ln568_fu_418_p2(35 downto 9);
    m_fix_back_fu_1693_p3 <= 
        shl_ln546_fu_1681_p2 when (tmp_1_reg_2347_pp0_iter5_reg(0) = '1') else 
        ashr_ln546_fu_1687_p2;
    m_fix_hi_fu_1615_p4 <= m_fix_0_in_in_v_v_fu_1590_p3(65 downto 53);
    m_fix_l_fu_1670_p3 <= 
        trunc_ln545_fu_1662_p1 when (tmp_1_reg_2347_pp0_iter5_reg(0) = '1') else 
        trunc_ln545_1_fu_1666_p1;
    mul_ln44_1_fu_427_p0 <= mul_ln44_1_fu_427_p00(41 - 1 downto 0);
    mul_ln44_1_fu_427_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(z2_fu_651_p4),47));
    mul_ln44_1_fu_427_p1 <= mul_ln44_1_fu_427_p10(6 - 1 downto 0);
    mul_ln44_1_fu_427_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_1_fu_665_p4),47));
    mul_ln44_2_fu_435_p0 <= mul_ln44_2_fu_435_p00(44 - 1 downto 0);
    mul_ln44_2_fu_435_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(z3_reg_2288),50));
    mul_ln44_2_fu_435_p1 <= mul_ln44_2_fu_435_p10(6 - 1 downto 0);
    mul_ln44_2_fu_435_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_3_reg_2299),50));
    mul_ln44_fu_620_p0 <= zext_ln42_1_fu_592_p1(39 - 1 downto 0);
    mul_ln44_fu_620_p1 <= mul_ln44_fu_620_p10(4 - 1 downto 0);
    mul_ln44_fu_620_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_fu_550_p4),43));
    mul_ln522_fu_423_p0 <= zext_ln522_fu_1402_p1(23 - 1 downto 0);
    mul_ln522_fu_423_p1 <= zext_ln522_fu_1402_p1(23 - 1 downto 0);
    mul_ln616_fu_1867_p0 <= mul_ln616_fu_1867_p00(18 - 1 downto 0);
    mul_ln616_fu_1867_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z1P_m_1_fu_1833_p4),36));
    mul_ln616_fu_1867_p1 <= mul_ln616_fu_1867_p10(18 - 1 downto 0);
    mul_ln616_fu_1867_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_Z1_hi_fu_1843_p4),36));
    or_ln357_fu_1023_p2 <= (x_is_inf_fu_1018_p2 or x_is_0_fu_1013_p2);
    or_ln373_fu_1092_p2 <= (tmp_1_fu_1046_p3 or icmp_ln372_fu_1040_p2);
    or_ln378_1_fu_1144_p2 <= (y_is_0_fu_940_p2 or or_ln378_fu_1138_p2);
    or_ln378_fu_1138_p2 <= (x_is_p1_fu_962_p2 or and_ln378_fu_1132_p2);
    or_ln386_1_fu_1168_p2 <= (x_is_NaN_fu_1008_p2 or and_ln386_fu_1162_p2);
    or_ln386_2_fu_1174_p2 <= (y_is_NaN_fu_997_p2 or or_ln386_1_fu_1168_p2);
    or_ln386_3_fu_2035_p2 <= (or_ln386_2_reg_2362_pp0_iter10_reg or or_ln378_1_reg_2355_pp0_iter10_reg);
    or_ln386_fu_1150_p2 <= (y_is_int_fu_1112_p9 or y_is_inf_fu_985_p2);
    or_ln431_1_fu_1330_p2 <= (or_ln431_fu_1324_p2 or and_ln431_3_fu_1318_p2);
    or_ln431_2_fu_1336_p2 <= (or_ln431_1_fu_1330_p2 or and_ln431_1_fu_1306_p2);
    or_ln431_fu_1324_p2 <= (and_ln431_fu_1300_p2 or and_ln431_2_fu_1312_p2);
    or_ln438_1_fu_1372_p2 <= (or_ln438_fu_1366_p2 or and_ln438_3_fu_1360_p2);
    or_ln438_2_fu_1378_p2 <= (or_ln438_1_fu_1372_p2 or and_ln438_fu_1342_p2);
    or_ln438_fu_1366_p2 <= (and_ln438_2_fu_1354_p2 or and_ln438_1_fu_1348_p2);
    or_ln628_fu_1931_p2 <= (icmp_ln628_1_fu_1925_p2 or and_ln628_fu_1911_p2);
    out_exp_fu_2018_p2 <= std_logic_vector(unsigned(trunc_ln657_reg_2484) + unsigned(ap_const_lv8_7F));
    out_sig_fu_1963_p3 <= 
        tmp_11_fu_1943_p4 when (tmp_14_fu_1891_p3(0) = '1') else 
        tmp_12_fu_1953_p4;
    pow_reduce_anonymous_namespace_log0_lut_table_array_address0 <= zext_ln502_fu_481_p1(6 - 1 downto 0);

    pow_reduce_anonymous_namespace_log0_lut_table_array_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            pow_reduce_anonymous_namespace_log0_lut_table_array_ce0_local <= ap_const_logic_1;
        else 
            pow_reduce_anonymous_namespace_log0_lut_table_array_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_address0 <= zext_ln502_fu_481_p1(6 - 1 downto 0);

    pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_ce0_local <= ap_const_logic_1;
        else 
            pow_reduce_anonymous_namespace_log_inverse_lut_table_pow_0_5_64_array_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_address0 <= zext_ln46_2_fu_782_p1(6 - 1 downto 0);

    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_ce0_local <= ap_const_logic_1;
        else 
            pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_address0 <= zext_ln46_fu_661_p1(4 - 1 downto 0);

    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_ce0_local <= ap_const_logic_1;
        else 
            pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_address0 <= zext_ln46_1_fu_757_p1(6 - 1 downto 0);

    pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_ce0_local <= ap_const_logic_1;
        else 
            pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_address0 <= zext_ln611_fu_1800_p1(9 - 1 downto 0);

    pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_ce0_local <= ap_const_logic_1;
        else 
            pow_reduce_anonymous_namespace_table_exp_Z1_ap_ufixed_array_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_address0 <= zext_ln159_fu_1815_p1(5 - 1 downto 0);

    pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_ce0_local_assign_proc : process(ap_block_pp0_stage0_11001)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
            pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_ce0_local <= ap_const_logic_1;
        else 
            pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    r_exp_1_fu_1899_p2 <= std_logic_vector(signed(r_exp_reg_2446_pp0_iter9_reg) + signed(ap_const_lv10_3FF));
    r_exp_2_fu_1904_p3 <= 
        r_exp_reg_2446_pp0_iter9_reg when (tmp_14_fu_1891_p3(0) = '1') else 
        r_exp_1_fu_1899_p2;
    r_exp_fu_1759_p3 <= 
        select_ln563_fu_1751_p3 when (tmp_13_fu_1729_p3(0) = '1') else 
        tmp_10_cast_fu_1720_p4;
    r_sign_fu_1294_p2 <= (y_is_odd_1_fu_1274_p9 and x_is_neg_fu_1035_p2);
    retval_2_fu_2149_p18 <= t_3_fu_2023_p4;
    retval_2_fu_2149_p19 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    retval_2_fu_2149_p20 <= (((((((or_ln378_1_reg_2355_pp0_iter10_reg & and_ln342_fu_2045_p2) & and_ln386_1_fu_2055_p2) & and_ln431_4_fu_2071_p2) & and_ln438_4_fu_2082_p2) & and_ln629_fu_2098_p2) & and_ln629_1_fu_2108_p2) & and_ln645_1_fu_2124_p2);
    retval_2_fu_2149_p4 <= t_fu_1975_p3;
    select_ln42_fu_608_p3 <= 
        tmp_3_fu_596_p3 when (tmp_5_fu_564_p3(0) = '1') else 
        zext_ln42_2_fu_604_p1;
    select_ln545_fu_1528_p3 <= 
        sext_ln545_fu_1524_p1 when (tmp_1_reg_2347(0) = '1') else 
        m_exp_reg_2334;
    select_ln553_1_fu_1582_p3 <= 
        shl_ln553_fu_1570_p2 when (tmp_9_fu_1547_p3(0) = '1') else 
        ashr_ln553_fu_1576_p2;
    select_ln553_fu_1555_p3 <= 
        m_exp_reg_2334 when (tmp_9_fu_1547_p3(0) = '1') else 
        sext_ln545_fu_1524_p1;
    select_ln563_fu_1751_p3 <= 
        add_ln563_1_fu_1745_p2 when (icmp_ln563_fu_1739_p2(0) = '1') else 
        tmp_10_cast_fu_1720_p4;
        sext_ln525_1_fu_1456_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(log_sum_1_reg_2314),65));

        sext_ln525_fu_1452_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln2_fu_1444_p3),65));

        sext_ln545_1_fu_1645_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln545_reg_2410),32));

        sext_ln545_fu_1524_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln545_fu_1519_p2),9));

        sext_ln552_fu_1534_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m_exp_reg_2334),32));

        sext_ln553_fu_1562_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln553_fu_1555_p3),32));

        sext_ln628_fu_1700_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(m_fix_back_fu_1693_p3),67));

    shl_ln1_fu_1417_p3 <= (tmp_8_reg_2319 & ap_const_lv24_0);
    shl_ln2_fu_1444_p3 <= (Elog2_fu_413_p2 & ap_const_lv12_0);
    shl_ln3_fu_1709_p3 <= (tmp_10_reg_2420_pp0_iter6_reg & ap_const_lv15_4000);
    shl_ln44_1_fu_835_p3 <= (mul_ln44_2_fu_435_p2 & ap_const_lv6_0);
    shl_ln44_2_fu_626_p3 <= (trunc_ln39_reg_2268 & ap_const_lv22_0);
    shl_ln44_3_fu_697_p3 <= (tmp_6_fu_687_p4 & ap_const_lv14_0);
    shl_ln44_4_fu_814_p3 <= (tmp_7_reg_2304 & ap_const_lv24_0);
    shl_ln4_fu_1873_p3 <= (add_ln616_fu_1853_p2 & ap_const_lv17_0);
    shl_ln545_fu_1657_p2 <= std_logic_vector(shift_left(unsigned(m_frac_l_reg_2403),to_integer(unsigned('0' & zext_ln545_fu_1648_p1(31-1 downto 0)))));
    shl_ln546_fu_1681_p2 <= std_logic_vector(shift_left(unsigned(m_fix_l_fu_1670_p3),to_integer(unsigned('0' & zext_ln546_fu_1677_p1(31-1 downto 0)))));
    shl_ln552_fu_1541_p2 <= std_logic_vector(shift_left(unsigned(m_frac_l_fu_431_p2),to_integer(unsigned('0' & zext_ln552_fu_1537_p1(31-1 downto 0)))));
    shl_ln553_fu_1570_p2 <= std_logic_vector(shift_left(unsigned(m_frac_l_fu_431_p2),to_integer(unsigned('0' & zext_ln553_fu_1566_p1(31-1 downto 0)))));
    shl_ln_fu_729_p3 <= (mul_ln44_1_fu_427_p2 & ap_const_lv1_0);
    sub_ln422_fu_1230_p2 <= std_logic_vector(unsigned(ap_const_lv9_96) - unsigned(zext_ln317_1_fu_930_p1));
    sub_ln44_1_fu_741_p2 <= std_logic_vector(unsigned(add_ln44_1_fu_713_p2) - unsigned(zext_ln44_7_fu_737_p1));
    sub_ln44_2_fu_847_p2 <= std_logic_vector(unsigned(add_ln44_2_fu_829_p2) - unsigned(zext_ln44_11_fu_843_p1));
    sub_ln44_fu_645_p2 <= std_logic_vector(unsigned(add_ln44_fu_637_p2) - unsigned(zext_ln44_2_fu_642_p1));
    sub_ln522_fu_1428_p2 <= std_logic_vector(unsigned(shl_ln1_fu_1417_p3) - unsigned(zext_ln522_1_fu_1424_p1));
    sub_ln545_fu_1519_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(es_exp_reg_2329));
    sub_ln574_fu_1781_p2 <= std_logic_vector(unsigned(m_fix_reg_2415_pp0_iter8_reg) - unsigned(m_fix_a_fu_1771_p4));
    t_1_fu_1996_p3 <= (r_sign_reg_2373_pp0_iter10_reg & ap_const_lv31_7F800000);
    t_2_fu_2007_p3 <= (r_sign_reg_2373_pp0_iter10_reg & ap_const_lv31_0);
    t_3_fu_2023_p4 <= ((r_sign_reg_2373_pp0_iter10_reg & out_exp_fu_2018_p2) & out_sig_reg_2479);
    t_fu_1975_p3 <= (r_sign_reg_2373_pp0_iter10_reg & ap_const_lv31_3F800000);
    tmp_10_cast_fu_1720_p4 <= grp_fu_2193_p3(24 downto 15);
    tmp_11_fu_1943_p4 <= add_ln616_1_fu_1885_p2(42 downto 20);
    tmp_12_fu_1953_p4 <= add_ln616_1_fu_1885_p2(41 downto 19);
    tmp_13_fu_1729_p3 <= grp_fu_2193_p3(24 downto 24);
    tmp_14_fu_1891_p3 <= add_ln616_1_fu_1885_p2(43 downto 43);
    tmp_15_fu_1915_p4 <= r_exp_2_fu_1904_p3(9 downto 7);
    tmp_1_fu_1046_p3 <= m_exp_fu_934_p2(8 downto 8);
    tmp_2_fu_1198_p3 <= b_exp_fu_924_p2(8 downto 8);
    tmp_3_fu_596_p3 <= (ap_const_lv1_1 & zext_ln42_1_fu_592_p1);
    tmp_5_fu_564_p3 <= b_frac1_fu_532_p2(24 downto 24);
    tmp_6_fu_687_p4 <= sub_ln44_fu_645_p2(37 downto 3);
    tmp_9_fu_1547_p3 <= sub_ln545_fu_1519_p2(7 downto 7);
    tmp_s_fu_572_p3 <= (trunc_ln516_fu_538_p1 & ap_const_lv13_0);
    trunc_ln39_fu_560_p1 <= b_frac1_fu_532_p2(21 - 1 downto 0);
    trunc_ln516_fu_538_p1 <= b_frac1_fu_532_p2(25 - 1 downto 0);
    trunc_ln545_1_fu_1666_p1 <= shl_ln545_fu_1657_p2(66 - 1 downto 0);
    trunc_ln545_fu_1662_p1 <= ashr_ln545_fu_1652_p2(66 - 1 downto 0);
    trunc_ln563_fu_1736_p1 <= grp_fu_2193_p3(15 - 1 downto 0);
    trunc_ln657_fu_1971_p1 <= r_exp_2_fu_1904_p3(8 - 1 downto 0);
    x_abs_greater_1_fu_1206_p2 <= (tmp_2_fu_1198_p3 xor ap_const_lv1_1);
    x_is_0_fu_1013_p2 <= "1" when (bs_exp_reg_2209_pp0_iter3_reg = ap_const_lv8_0) else "0";
    x_is_1_fu_952_p2 <= (icmp_ln340_fu_946_p2 and icmp_ln340_1_reg_2247_pp0_iter3_reg);
    x_is_NaN_fu_1008_p2 <= (icmp_ln18_4_reg_2253_pp0_iter3_reg and icmp_ln18_3_fu_1003_p2);
    x_is_inf_fu_1018_p2 <= (icmp_ln340_1_reg_2247_pp0_iter3_reg and icmp_ln18_3_fu_1003_p2);
    x_is_n1_fu_968_p2 <= (x_is_1_fu_952_p2 and tmp_reg_2224_pp0_iter3_reg);
    x_is_neg_fu_1035_p2 <= (xor_ln357_fu_1029_p2 and tmp_reg_2224_pp0_iter3_reg);
    x_is_p1_fu_962_p2 <= (xor_ln341_fu_957_p2 and x_is_1_fu_952_p2);
    xor_ln341_fu_957_p2 <= (tmp_reg_2224_pp0_iter3_reg xor ap_const_lv1_1);
    xor_ln342_fu_2060_p2 <= (x_is_n1_reg_2341_pp0_iter10_reg xor ap_const_lv1_1);
    xor_ln357_fu_1029_p2 <= (or_ln357_fu_1023_p2 xor ap_const_lv1_1);
    xor_ln373_fu_1098_p2 <= (or_ln373_fu_1092_p2 xor ap_const_lv1_1);
    xor_ln386_1_fu_2039_p2 <= (or_ln386_3_fu_2035_p2 xor ap_const_lv1_1);
    xor_ln386_2_fu_2050_p2 <= (or_ln378_1_reg_2355_pp0_iter10_reg xor ap_const_lv1_1);
    xor_ln386_fu_1156_p2 <= (or_ln386_fu_1150_p2 xor ap_const_lv1_1);
    xor_ln421_fu_1248_p2 <= (icmp_ln421_fu_1212_p2 xor ap_const_lv1_1);
    xor_ln431_fu_1986_p2 <= (or_ln431_2_reg_2381_pp0_iter10_reg xor ap_const_lv1_1);
    xor_ln438_fu_1991_p2 <= (or_ln438_2_reg_2387_pp0_iter10_reg xor ap_const_lv1_1);
    xor_ln628_fu_2114_p2 <= (or_ln628_reg_2468 xor ap_const_lv1_1);
    xor_ln629_fu_2103_p2 <= (tmp_16_reg_2430_pp0_iter10_reg xor ap_const_lv1_1);
    y_is_0_fu_940_p2 <= "1" when (es_exp_fu_909_p3 = ap_const_lv8_0) else "0";
    y_is_NaN_fu_997_p2 <= (icmp_ln18_fu_973_p2 and icmp_ln18_2_fu_991_p2);
    y_is_inf_fu_985_p2 <= (icmp_ln18_fu_973_p2 and icmp_ln18_1_fu_979_p2);
    y_is_int_fu_1112_p4 <= "1" when (and_ln373_1_fu_1080_p2 = ap_const_lv23_0) else "0";
    y_is_int_fu_1112_p7 <= "X";
    y_is_int_fu_1112_p8 <= (icmp_ln372_fu_1040_p2 & xor_ln373_fu_1098_p2);
    y_is_ninf_fu_1192_p2 <= (y_is_inf_fu_985_p2 and es_sign_fu_901_p3);
    y_is_odd_1_fu_1274_p7 <= "X";
    y_is_odd_1_fu_1274_p8 <= (icmp_ln421_fu_1212_p2 & and_ln422_1_fu_1260_p2);
        y_is_odd_fu_1240_p2 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln422_fu_1230_p2),32));

    y_is_pinf_fu_1186_p2 <= (y_is_pos_fu_1180_p2 and y_is_inf_fu_985_p2);
    y_is_pos_fu_1180_p2 <= (es_sign_fu_901_p3 xor ap_const_lv1_1);
    z1_fu_542_p3 <= (trunc_ln516_fu_538_p1 & ap_const_lv14_0);
    z2_fu_651_p4 <= sub_ln44_fu_645_p2(43 downto 3);
    zext_ln134_1_fu_795_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_7_6_64_array_q0),50));
    zext_ln134_2_fu_853_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_12_6_64_array_q0),50));
    zext_ln134_fu_787_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pow_reduce_anonymous_namespace_log_lut_table_ap_fixed_4_4_16_array_q0),56));
    zext_ln142_fu_868_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln142_1_fu_862_p2),56));
    zext_ln159_fu_1815_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Z2_ind_fu_1805_p4),64));
    zext_ln160_1_fu_1823_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pow_reduce_anonymous_namespace_table_f_Z2_ap_ufixed_array_q0),19));
    zext_ln160_fu_1820_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_diff_lo_reg_2453),19));
    zext_ln317_1_fu_930_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(es_exp_fu_909_p3),9));
    zext_ln317_fu_921_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bs_exp_reg_2209_pp0_iter3_reg),9));
    zext_ln373_fu_1070_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln373_fu_1064_p2),23));
    zext_ln40_1_fu_803_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(z3_reg_2288),56));
    zext_ln40_fu_675_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(z2_fu_651_p4),48));
    zext_ln42_1_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(z1_fu_542_p3),43));
    zext_ln42_2_cast_fu_584_p3 <= (ap_const_lv1_1 & zext_ln42_fu_580_p1);
    zext_ln42_2_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln42_2_cast_fu_584_p3),44));
    zext_ln42_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_572_p3),42));
    zext_ln44_10_fu_825_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(eZ_1_fu_806_p3),63));
    zext_ln44_11_fu_843_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln44_1_fu_835_p3),63));
    zext_ln44_2_fu_642_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln44_reg_2278),44));
    zext_ln44_3_fu_705_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln44_3_fu_697_p3),50));
    zext_ln44_4_fu_709_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(eZ_fu_679_p3),50));
    zext_ln44_7_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_729_p3),50));
    zext_ln44_9_fu_821_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln44_4_fu_814_p3),63));
    zext_ln44_fu_633_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln44_2_fu_626_p3),44));
    zext_ln46_1_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_1_fu_665_p4),64));
    zext_ln46_2_fu_782_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_3_fu_762_p4),64));
    zext_ln46_fu_661_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_reg_2263),64));
    zext_ln485_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_frac_1_fu_506_p3),25));
    zext_ln502_fu_481_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(index0_fu_471_p4),64));
    zext_ln522_1_fu_1424_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_1407_p4),63));
    zext_ln522_fu_1402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zk_trunc_reg_2324),45));
    zext_ln525_fu_1465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln522_1_fu_1434_p4),65));
    zext_ln532_fu_1493_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_frac_fu_1485_p3),25));
    zext_ln545_fu_1648_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln545_1_fu_1645_p1),67));
    zext_ln546_fu_1677_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln545_1_fu_1645_p1),66));
    zext_ln549_fu_1601_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_1597_p1),67));
    zext_ln552_fu_1537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln552_fu_1534_p1),67));
    zext_ln553_fu_1566_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln553_fu_1562_p1),67));
    zext_ln611_fu_1800_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m_diff_hi_fu_1786_p4),64));
    zext_ln616_2_fu_1881_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln616_fu_1867_p2),44));
end behav;
